#!/usr/bin/env python3
"""Generate tables.asm for NFX4P from formulas (the exporter never runs this).

ctl:  eight 128-entry control tables, one per knob, in knob order. The DSP rounds
      each raw knob word to 0..127 and copies ctl[128*knob + value] to the voice
      block. The values are NFX-4P's original ColdFire packet words: 65 even-knob
      samples, odd knobs the floored average of their neighbours, 127 exact.
tanh: tanh(8 m) for m = 0..1 in 1,024 intervals (1,025 words, Q23).

    python make_tables.py            # rewrite tables.asm
    python make_tables.py --check    # fail if tables.asm differs
"""
import argparse
import math
from pathlib import Path

Q = 1 << 23
TEMPO = 2880          # gate lengths at 120 BPM (BPM x 24): the DSP has no tempo


def lookup(fn, k):
    """The 65-entry interpolated lookup the original ColdFire handler used."""
    if k == 127:
        return fn(127)
    v = fn(2 * (k // 2))
    return (v + fn(min(127, 2 * (k // 2) + 2))) // 2 if k & 1 else v


def cutoff(k):          # FREQ: dt base, 0.001 + 2.25 c^4 (as NFX-SV)
    return lookup(lambda k: round(Q * min(1.125, (.001 + 2.25 * (k / 127) ** 4) / 2) / 2), k)


def stage_samples(k):   # ATK/DEC time curve: 1 ms .. 10 s, squared
    return 44100 * .001 * (1 + 99 * max(0, k - 1) / 126) ** 2


def attack(k):
    """Charge coefficient alpha (to 2x full scale, peak at full scale): bits 0-22
    mantissa, bit 23 set when the mantissa is alpha * 2^31 rather than * 2^23."""
    if not k:
        return Q - 1
    v = lookup(lambda k: max(1, round((1 << 31) * -math.expm1(-math.log(2) / stage_samples(k)))), k)
    return v >> 8 if v >= Q else v | Q


def decay(k):           # DEC: exponential discharge to -96 dB
    if not k:
        return Q - 1
    return lookup(lambda k: max(1, min(Q - 1, round(Q * -math.expm1(-math.log(65536) / stage_samples(k))))), k)


def depth(k):           # ENVA: bipolar, 64 neutral
    def fn(k):
        d = k - 64
        if not d:
            return 0
        limit = 64 if d < 0 else 63
        return (-1 if d < 0 else 1) * round(limit * 73728 * math.expm1(4 * abs(d) / limit) / math.expm1(4))
    return lookup(fn, k)


def resonance(k):       # RESO: fb/8 with fb = 5 k/127
    return (k * 5242880 + 63) // 127


def mode(k):            # MODE: sign bit set (2nd pole) from 64 up
    return k << 17 if k < 64 else (0xFFFFFF if k == 127 else Q + (k - 64) * 133152)


def gain(k):            # GAIN: gain^4 / 4 (uLADR drive, input / 16)
    return lookup(lambda k: round(Q * (k / 127) ** 4 / 4), k)


def vca(k):             # VCA: 127 bypass (0), 64-126 envelope (1), 0-63 gate samples
    if k == 127:
        return 0
    if k >= 64:
        return 1
    return max(2, ((((k + 1) * 128) * 44100) >> 10) * 360 // TEMPO)


KNOBS = (cutoff, resonance, mode, depth, attack, decay, gain, vca)


def tables():
    ctl = [fn(k) & 0xFFFFFF for fn in KNOBS for k in range(128)]
    tanh = [round(Q * math.tanh(8 * i / 1024)) for i in range(1025)]
    return {'ctl': ctl, 'tanh': tanh}


def content():
    out = ['; GENERATED by make_tables.py: edit that file, not this one.\n']
    for name, words in tables().items():
        out.append(f'{name}:\n')
        for i in range(0, len(words), 8):
            out.append('    .dc ' + ','.join(f'${w:06x}' for w in words[i:i + 8]) + '\n')
    return ''.join(out)


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    path = Path(__file__).with_name('tables.asm')
    if a.check:
        if path.read_text() != content():
            raise SystemExit('tables.asm differs from make_tables.py')
    else:
        path.write_text(content())
