"""Generate a correctness-first fixed-point translation of Simple606 BassDrum.

Derived signal path: Copyright (c) 2026 Matthew Fecher (MIT; see LICENSE-Simple606).
Audio/filter state is Q21 (actual audio / 4 in DSP fractional arithmetic).
Envelope state is Q23, body amplitude is stored divided by two, phase wraps at
2^24. Lookup tables translate the source's trigger math; they are not samples.
This initial implementation floors modulated controls to their 7-bit setting.
"""
import json
import math
from pathlib import Path
from mds_build import ROOT

Q = 1 << 23
FS = 44100
STATE = 'active phase freq target pitch amp ampcoef clickenv clickcoef impenv impcoef clickgain impgain bodylp clicklp implp z1 z2 lastbody rnglo rnghi noisein noiseout dcin dcout silent body click delta rngtemp temp heatgain heatnorm phasefrac freqerr amperr clickenverr impenverr dcerr'.split()
S = {name: f'x:(r6+${i:x})' for i,name in enumerate(STATE)}


def word(value):
    n = round(value*Q)
    if not -Q <= n <= Q:
        raise ValueError(f'Fraction out of range: {value}')
    return min(Q-1,n) & 0xffffff


def generate():
    code = ['; GENERATED by tools/generate_bd.py. Edit the generator, then regenerate.',
            '; Signal path derived from Simple606; see LICENSE-Simple606.',
            '; No timing qualification: draft only.']
    tables = {}
    def emit(*lines): code.extend(lines)
    def load(name, reg='a'): emit(f'    move {S[name]},{reg}')
    def save(name, reg='a1'): emit(f'    move {reg},{S[name]}')
    def imm(value, reg='x0'): emit(f'    move #>${word(value):06x},{reg}')
    def mul(value):
        shift = 0
        while abs(value) >= 1:
            value /= 2; shift += 1
        emit('    move a1,x0'); imm(value,'y0'); emit('    mpy x0,y0,a')
        if shift: emit(f'    asl #{shift},a,a')
    def param(index):
        emit(f'    move y:(r6+${index+1:x}),a', '    asr #7,a,a',
             '    and #>$7f,a', '    move a1,n0')
    def lookup(label, state):
        emit(f'    move #>{label},r0', '    nop', '    move p:(r0+n0),x0')
        save(state,'x0')
    def decay(env, coefficient):
        load(env,'x0'); load(coefficient,'y0'); emit('    mpy x0,y0,a')
        # Retain sub-word decay updates instead of shortening quiet tails.
        emit('    clr b'); load(env+'err','b0'); emit('    add b,a'); save(env+'err','a0')
        # Match the source's 1e-6 cutoff, with body stored at half amplitude.
        threshold = 4 if env=='amp' else 8
        emit(f'    move #>{threshold},x0', '    cmp x0,a', '    clr b', '    tlt b,a')
        save(env)
    def lowpass(state, hz):
        load(state,'x0'); emit('    sub x0,a', '    move a1,y0')
        imm(1-math.exp(-2*math.pi*hz/FS),'x1')
        emit('    mpy x1,y0,a', '    add x0,a'); save(state)
    def tanh():
        # Q21 input, linear interpolation between intervals of 1/1024 actual.
        emit('    move a1,b','    and #>$7ff,b','    asl #12,b,b','    move b1,y1',
             '    asr #11,a,a', '    add #>$001000,a', '    move a1,n0',
             '    move #>tanh_table,r0','    nop','    move p:(r0+n0),x0',
             '    move #>tanh_table+1,r0','    nop','    move p:(r0+n0),a',
             '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a')
    emit('init:', '    clr a')
    for name in STATE: save(name)
    emit('    move #>$606606,x0'); save('rnglo','x0')
    emit('    rts', 'trigger:')
    param(0)
    for name in ('amp','freq','pitch','clickcoef','impcoef','clickgain','impgain'):
        lookup('t_'+name,name)
    # Envelopes use max(old,new), as in DecayEnvelope::trigger().
    load('clickenv','y0'); lookup('t_clickenv','temp'); load('temp')
    emit('    cmp y0,a', '    tlt y0,a'); save('clickenv')
    load('impenv','y0'); lookup('t_impenv','temp'); load('temp')
    emit('    cmp y0,a', '    tlt y0,a'); save('impenv')
    param(2)
    lookup('t_tune','temp')
    load('freq','x0'); load('temp','y0'); emit('    mpy x0,y0,a','    asl #2,a,a'); save('freq')
    emit(f'    move #>{round(51.24*(1<<30)/FS)},x0','    mpy x0,y0,a','    asl #2,a,a'); save('target')
    param(1)
    emit('    move y:(r6+$5),a','    tst a','    jeq normal_decay')
    lookup('t_decay_xl','ampcoef'); emit('    jmp decay_ready','normal_decay:')
    lookup('t_decay','ampcoef'); emit('decay_ready:')
    emit(f'    move #>${round((1-.165)*(1<<24)):06x},x0'); save('phase','x0')
    emit('    clr a'); save('lastbody'); save('silent'); save('phasefrac'); save('freqerr'); save('amperr')
    emit('    move #>1,x0'); save('active','x0'); emit('    rts','render:')
    load('active'); emit('    tst a','    jeq silent_block')
    param(3); lookup('t_heatgain','heatgain'); lookup('t_heatnorm','heatnorm')
    emit('    do #32,block_end','sample:')
    load('active'); emit('    tst a','    jeq sample_silent')
    # Exact xorshift32 expressed as a low-24/high-8 pair.
    load('rnglo','x0'); load('rnglo'); emit('    asl #13,a,a', '    eor x0,a'); save('rngtemp')
    load('rnglo'); emit('    asr #11,a,a','    and #>$ff,a'); load('rnghi','x0')
    emit('    eor x0,a'); save('rnghi')
    # ASR leaves discarded bits in A0; clear them before the next left shift.
    load('rnghi')
    emit('    asl #7,a,a','    move a1,x0'); load('rngtemp')
    emit('    asr #17,a,a','    and #>$7f,a','    or x0,a'); load('rngtemp','x0')
    emit('    eor x0,a'); save('rngtemp')
    emit('    asr #19,a,a','    and #>$1f,a','    move a1,x0'); load('rnghi')
    emit('    asl #5,a,a','    or x0,a'); load('rnghi','x0')
    emit('    eor x0,a','    and #>$ff,a'); save('rnghi')
    load('rngtemp'); emit('    asl #5,a,a'); load('rngtemp','x0'); emit('    eor x0,a'); save('rnglo')
    emit('    asr #9,a,a','    and #>$7fff,a','    move a1,x0'); load('rnghi')
    emit('    asl #15,a,a','    or x0,a','    sub #>$400000,a','    asr #1,a,a')
    # DC-filtered noise, scaled /4.
    load('noisein','x0'); save('noisein'); emit('    sub x0,a','    move a1,b')
    load('noiseout'); mul(.995); emit('    add b,a'); save('noiseout')
    lowpass('clicklp',1400)
    decay('clickenv','clickcoef'); emit('    move a1,y0'); load('clicklp','x0'); emit('    mpy x0,y0,a')
    load('clickgain','y0'); emit('    move a1,x0','    mpy x0,y0,a'); save('click')
    # Swept sine body. Frequency changes before the phase increment, as upstream.
    load('target'); load('freq','x0'); emit('    sub x0,a','    move a1,y0'); load('pitch','x1')
    emit('    mpy x1,y0,a','    clr b'); load('freqerr','b0')
    emit('    add b,a'); save('freqerr','a0'); emit('    add x0,a'); save('freq')
    # Six fractional frequency bits prevent cumulative pitch-sweep truncation.
    load('phasefrac','x0'); emit('    add x0,a','    move a1,b','    and #>$3f,b'); save('phasefrac','b1')
    emit('    asr #6,a,a'); load('phase','x0'); emit('    add x0,a'); save('phase')
    emit('    asr #9,a,a','    and #>$7fff,a','    move a1,r0',
         '    move x:(r0+>mds_sine),x0')
    load('amp','y0'); emit('    mpy x0,y0,a','    asr #1,a,a')
    load('lastbody','x0'); save('lastbody'); emit('    move a1,b','    sub x0,a'); save('delta')
    emit('    move b1,a'); lowpass('bodylp',620+(1200-620)*.34)
    mul(.92+.18*.10); save('body'); decay('amp','ampcoef')
    # Impulse: differentiated body -> source high-pass biquad -> low-pass.
    w=2*math.pi*1350/FS; c=math.cos(w); alpha=math.sin(w)/(2*.707); norm=1/(1+alpha)
    b0=(1+c)*.5*norm; b1=-(1+c)*norm; b2=b0; a1=-2*c*norm; a2=(1-alpha)*norm
    load('delta'); mul(b0); load('z1','x0'); emit('    add x0,a'); save('temp')
    load('delta'); mul(b1); emit('    move a1,b'); load('temp'); mul(-a1)
    emit('    add b,a'); load('z2','x0'); emit('    add x0,a'); save('z1')
    load('delta'); mul(b2); emit('    move a1,b'); load('temp'); mul(-a2)
    emit('    add b,a'); save('z2'); load('temp'); lowpass('implp',2600)
    decay('impenv','impcoef'); emit('    move a1,y0'); load('implp','x0')
    emit('    mpy x0,y0,a','    move a1,x0'); load('impgain','y0')
    emit('    mpy x0,y0,a','    asl #1,a,a'); load('body','x0'); emit('    add x0,a')
    load('click','x0'); emit('    add x0,a'); mul(1.12+.18*.12); tanh()
    # Output DC blocker and source voice trim.
    load('dcin','x0'); save('dcin'); emit('    sub x0,a','    move a1,b')
    load('dcout'); mul(.995)
    emit('    move b1,y0','    clr b'); load('dcerr','b0')
    emit('    add b,a'); save('dcerr','a0'); emit('    add y0,a'); save('dcout'); mul(.70)
    emit('    move a1,b', '    asl #2,b,b'); save('temp','b1')
    # Plugin heat is evaluated per render, rather than captured at trigger.
    emit('    move y:(r6+$4),x0','    move a1,b','    move x0,a','    tst a',
         '    move b1,a','    jeq heat_done')
    load('heatgain','y0'); emit('    move a1,x0','    mpy x0,y0,a','    asl #3,a,a'); tanh()
    load('heatnorm','y0'); emit('    move a1,x0','    mpy x0,y0,a','heat_done:')
    emit('    asl #2,a,a','    move a,y:(r7)+')
    load('amp'); load('clickenv','x0'); emit('    or x0,a'); load('impenv','x0')
    emit('    or x0,a','    jne reset_silence')
    load('temp'); emit('    abs a','    move #>84,x0','    cmp x0,a','    jge reset_silence')
    load('silent'); emit('    add #>1,a'); save('silent')
    emit('    move #>32,x0','    cmp x0,a','    jlt sample_done','    clr a'); save('active')
    emit('    jmp sample_done','reset_silence:','    clr a'); save('silent')
    emit('    jmp sample_done','sample_silent:','    clr a','    move a,y:(r7)+',
         'sample_done:','    nop','block_end:','    rts','silent_block:','    clr a','    do #32,zero_end',
         '    move a,y:(r7)+','zero_end:','    rts')
    for name in ('amp','freq','pitch','clickenv','clickcoef','impenv','impcoef','clickgain','impgain'):
        tables['t_'+name]=[]
    for i in range(128):
        transient=(i/127)**.75; shape=.1+transient*.5; thud=shape*shape
        values=dict(amp=(1+thud*.22)/2, freq=116.48*(1+thud*.28)*128/FS,
                    pitch=1-math.exp(-1/(FS*(.022-.014*thud))),
                    clickenv=.04+shape*.34, clickcoef=math.exp(-1/(FS*(.002+shape*.0085))),
                    impenv=.06+shape*.55+thud*.08, impcoef=math.exp(-1/(FS*(.0008+shape*.008))),
                    clickgain=.06+shape*.9, impgain=(.08+shape*2.2)/2)
        for name,value in values.items(): tables['t_'+name].append(word(value))
    tables['t_tune']=[word(2**((-12+24*i/127)/12)/4) for i in range(128)]
    for name,scale in (('t_decay',.45),('t_decay_xl',1)):
        tables[name]=[word(math.exp(-1/(FS*(.22+(-1.75+4.75*(i/127*scale)**2)*.12)))) for i in range(128)]
    tables['t_heatgain']=[word((1+3.5*i/127)/8) for i in range(128)]
    tables['t_heatnorm']=[word(1/math.sqrt(1+3.5*i/127)) for i in range(128)]
    tables['tanh_table']=[word(math.tanh((i-4096)/1024)/4) for i in range(8193)]
    for name,values in tables.items():
        emit(name+':')
        for i in range(0,len(values),8): emit('    .dc '+','.join(f'${w:06x}' for w in values[i:i+8]))
    return '\n'.join(code)+'\n'


def main():
    destination=ROOT/'machines/bd'
    destination.mkdir(parents=True,exist_ok=True)
    (destination/'bd.asm').write_text(generate())
    manifest=dict(id='org.kitbasher.tr6.bd',display_name='TR6 BASS DRUM',category='TR6',short_label='BD',
                  machine_version='0.1', params=[
        dict(name='TRAN',default=51,transform='raw14'),
        dict(name='DEC',default=102,transform='raw14'),
        dict(name='TUNE',default=75,transform='raw14'),
        dict(name='HEAT',default=0,transform='raw14'),
        dict(name='XL',default=0,transform='boolean')])
    (destination/'bd.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(destination)


if __name__=='__main__': main()
