"""Correctness-first LT/HT translations from pinned Simple606; see LICENSE-Simple606.

Audio Q20; envelopes Q23 with retained product remainders; phase 24-bit with
four extra frequency bits. Trigger tables come directly from the source C++.
"""
import argparse
import json
import math
import os
from pathlib import Path

from mds_build import ROOT
from generate_bd import word
from render_bd import run

FS = 44100
OUTPUT_GAIN = .5
MODES = {'lt': [('main', 1, 2.2826), ('strike', 1.05, .2)],
         'ht': [('main', 1, 2.674), ('strike', .71, .420), ('lower', .09, 1.059),
                ('upper0', .002617, -2.987), ('upper1', .001954, .618),
                ('upper2', .003381, 1.002), ('upper3', .003546, .597)]}
RISES = ('bodyrise', 'strikerise', 'snaprise', 'noiserise')


def state_layout(kind):
    names = 'active frame duration lowlo lowhi highlo highhi taillo tailhi'.split()
    for name, _, _ in MODES[kind]:
        names += [name+s for s in ('phase', 'freq', 'frac', 'env', 'pole', 'enverr')]
    for name in ('snap', 'burst', 'tail'):
        names += [name+s for s in ('env', 'pole', 'enverr')]
    for name in RISES:
        names += [name, name+'err']
    if kind == 'lt': names += ['glide', 'glideerr']
    for i in range(6 if kind == 'ht' else 8):
        names += [f'f{i}{s}' for s in ('b0', 'a1', 'a2', 'z1', 'z2')]
    names += 'body harmonic excitation highwhite temp1 temp2 snap burst rngtemp'.split()
    assert len(names) <= 119
    return {name: ('X', i) if i<64 else ('Y', i-64+9) for i, name in enumerate(names)}


def build_reference(out, compiler='clang++'):
    out = Path(out).resolve(); out.mkdir(parents=True, exist_ok=True)
    exe = out / ('reference.exe' if os.name == 'nt' else 'reference')
    run([compiler, '-std=c++14', '-O2', '-I', ROOT/'.audit-sources/Simple606/Source',
         ROOT/'tests/tom_reference.cpp', '-o', exe])
    return exe


def generate(kind, controls):
    layout = state_layout(kind)
    S = {n: f'{s.lower()}:(r6+${i:x})' for n, (s, i) in layout.items()}
    lines = ['; GENERATED by tools/generate_toms.py; source Simple606 Toms.hpp.',
             '; See LICENSE-Simple606. Draft, not timing-qualified.',
             '; Audio Q20, envelopes Q23, phase frequency scaled by 16.']
    tables = {}
    def emit(*s): lines.extend(s)
    def load(n, r='a'): emit(f'    move {S[n]},{r}')
    def save(n, r='a1'): emit(f'    move {r},{S[n]}')
    def imm(v, r='x0'): emit(f'    move #>${word(v):06x},{r}')
    def mul(v):
        shift = 0
        while abs(v)>=1: v/=2; shift+=1
        emit('    move a1,x0'); imm(v, 'y0'); emit('    mpy x0,y0,a')
        if shift: emit(f'    asl #{shift},a,a')
    def mulstate(n):
        emit('    move a1,x0'); load(n, 'y0'); emit('    mpy x0,y0,a')
    def decay(n, coef):
        load(n, 'x0')
        if isinstance(coef, str): load(coef, 'y0')
        else: imm(coef, 'y0')
        emit('    mpy x0,y0,a', '    clr b'); load(n+'err', 'b0')
        emit('    add b,a'); save(n+'err', 'a0'); save(n)
    def rise(n):
        emit('    move #>$7fffff,a'); load(n, 'x0'); emit('    sub x0,a')
    def sine():
        emit('    asr #9,a,a', '    and #>$7fff,a', '    move a1,r0',
             '    move x:(r0+>mds_sine),a', '    asr #3,a,a')
    def lookup(label, n, values):
        tables[label] = values
        emit(f'    move #>{label},r0', '    nop', '    move p:(r0+n0),x0'); save(n, 'x0')
    def param(i):
        emit(f'    move y:(r6+${i+1:x}),a', '    asr #7,a,a', '    and #>$7f,a', '    move a1,n0')
    def noise(n):
        # Exact 32-bit xorshift in 24+8-bit limbs, matching the source stream.
        load(n+'lo', 'x0'); load(n+'lo'); emit('    asl #13,a,a', '    eor x0,a'); save('rngtemp')
        load(n+'lo'); emit('    asr #11,a,a', '    and #>$ff,a'); load(n+'hi', 'x0')
        emit('    eor x0,a'); save(n+'hi'); load(n+'hi'); emit('    asl #7,a,a', '    move a1,x0')
        load('rngtemp'); emit('    asr #17,a,a', '    and #>$7f,a', '    or x0,a'); load('rngtemp', 'x0')
        emit('    eor x0,a'); save('rngtemp')
        emit('    asr #19,a,a', '    and #>$1f,a', '    move a1,x0'); load(n+'hi')
        emit('    asl #5,a,a', '    or x0,a'); load(n+'hi', 'x0'); emit('    eor x0,a', '    and #>$ff,a'); save(n+'hi')
        load('rngtemp'); emit('    asl #5,a,a'); load('rngtemp', 'x0'); emit('    eor x0,a'); save(n+'lo')
        # Source uses top 24 bits / (2^24-1). The fixed map uses /2^24;
        # its bounded <=2^-23 discrepancy is included in audio comparisons.
        emit('    asr #8,a,a', '    and #>$ffff,a', '    move a1,x0'); load(n+'hi')
        emit('    asl #16,a,a', '    or x0,a', '    move #>$800000,x0', '    eor x0,a',
             '    move a1,a', '    asr #3,a,a')
    def filt(i):
        n = f'f{i}'
        mulstate(n+'b0'); emit('    asl #1,a,a'); save('temp1')
        load(n+'z1', 'x0'); emit('    add x0,a'); save('temp2')
        mulstate(n+'a1'); emit('    asl #1,a,a'); load(n+'z2', 'x0'); emit('    add x0,a')
        load('temp1', 'x0')
        op = 'sub' if i%2==0 else 'add'
        emit(f'    {op} x0,a', f'    {op} x0,a'); save(n+'z1')
        load('temp2'); mulstate(n+'a2'); emit('    asl #1,a,a'); load('temp1', 'x0')
        emit('    add x0,a'); save(n+'z2'); load('temp2')

    emit('init:', '    clr a')
    for n in layout: save(n)
    for n, xor in [('low',0x60001604), ('high',0x60001607), ('tail',0x60001605)]:
        seed = (0x6062 if kind=='ht' else 0x6061)^xor
        emit(f'    move #>${seed&0xffffff:06x},x0'); save(n+'lo', 'x0')
        emit(f'    move #>${seed>>24:06x},x0'); save(n+'hi', 'x0')
    emit('    rts', 'trigger:', '    clr a')
    for n in layout:
        if n not in ('lowlo','lowhi','highlo','highhi','taillo','tailhi'): save(n)
    param(0)
    lookup('t_duration', 'duration', [r['duration'] for r in controls['decay']])
    envs = [n for n, _, _ in MODES[kind]] + ['snap','burst','tail']
    for n in envs:
        lookup('t_'+n+'pole', n+'pole', [word(r[n]) for r in controls['decay']])
    param(1)
    for n, _, _ in MODES[kind]:
        lookup('t_'+n+'freq', n+'freq', [round(r[n]*(1<<28)/FS) for r in controls['pitch']])
    if kind=='lt': lookup('t_glide', 'glide', [round(r['glide']*(1<<28)/FS) for r in controls['pitch']])
    for i in range(6 if kind=='ht' else 8):
        for j, c in enumerate(('b0','a1','a2')):
            lookup(f't_f{i}{c}', f'f{i}{c}', [word(r['filters'][i][j]*(.5 if j==0 else -.5)) for r in controls['pitch']])
    emit('    move #>$7fffff,x0')
    for n in envs: save(n+'env', 'x0')
    for n in RISES: save(n, 'x0')
    for n, _, phase in MODES[kind]:
        emit(f'    move #>${round((phase/(2*math.pi)%1)*(1<<24)):06x},x0'); save(n+'phase','x0')
    emit('    move #>1,x0'); save('active','x0'); emit('    rts','render:')
    load('active'); emit('    tst a', '    jeq silent_block', '    do #32,block_end')
    load('active'); emit('    tst a', '    jeq sample_silent')
    for n, _, _ in MODES[kind]:
        load(n+'freq')
        if n=='main' and kind=='lt': load('glide','x0'); emit('    add x0,a')
        load(n+'frac','x0'); emit('    add x0,a','    move a1,b','    and #>$f,b'); save(n+'frac','b1')
        emit('    asr #4,a,a'); load(n+'phase','x0'); emit('    add x0,a'); save(n+'phase')
    for n, pole in zip(RISES, controls['rise_poles']): decay(n, pole)
    emit('    clr a'); save('harmonic')
    for harmonic, level in ((2,.0095),(3,.0032)):
        load('mainphase'); emit('    asl #1,a,a')
        if harmonic==3: load('mainphase','x0'); emit('    add x0,a')
        sine(); mul(level); load('harmonic','x0'); emit('    add x0,a'); save('harmonic')
    load('mainphase'); sine(); load('harmonic','x0'); emit('    add x0,a'); mulstate('mainenv'); save('body')
    for n, level, _ in MODES[kind][2:]:
        load(n+'phase'); sine(); mul(level); mulstate(n+'env'); load('body','x0'); emit('    add x0,a'); save('body')
    rise('bodyrise'); mulstate('body'); save('body')
    load('strikephase'); sine(); mul(MODES[kind][1][1]); mulstate('strikeenv'); save('temp1')
    rise('strikerise'); mulstate('temp1'); load('body','x0'); emit('    add x0,a'); save('body')
    rise('snaprise'); mulstate('snapenv'); save('snap')
    rise('noiserise'); mulstate('burstenv'); save('burst')
    # Each band has an independent RNG and its own HP/LP cascade.
    for band, fi, sl, bl in [('low',0,.5,.03), ('high',2,.03,.009)]:
        noise(band)
        if band=='high': save('highwhite')
        filt(fi); filt(fi+1); save('temp2')
        load('snap'); mul(sl); save('temp1'); load('burst'); mul(bl)
        load('temp1','x0'); emit('    add x0,a'); mulstate('temp2')
        if band=='high': load('excitation','x0'); emit('    add x0,a')
        save('excitation')
    noise('tail'); filt(4); filt(5); mul(.01); mulstate('tailenv'); save('temp1')
    rise('noiserise'); mulstate('temp1'); load('excitation','x0'); emit('    add x0,a'); save('excitation')
    if kind=='lt':
        load('highwhite'); filt(6); filt(7); mul(1.1); mulstate('snap')
        load('excitation','x0'); emit('    add x0,a'); save('excitation')
    load('body'); load('excitation','x0'); emit('    add x0,a'); mul(.8)
    emit('    asl #2,a,a','    move a,y:(r7)+')  # Q20 -> Q23 with output gain .5
    for n in envs: decay(n+'env',n+'pole')
    if kind=='lt': decay('glide',controls['glide_pole'])
    load('frame'); emit('    add #>1,a'); save('frame'); load('duration','x0')
    emit('    cmp x0,a','    jlt sample_done','    clr a'); save('active')
    emit('    jmp sample_done','sample_silent:','    clr a','    move a,y:(r7)+',
         'sample_done:','    nop','block_end:','    rts','silent_block:','    clr a',
         '    do #32,zero_end','    move a,y:(r7)+','zero_end:','    rts')
    for label, values in tables.items():
        emit(label+':')
        for i in range(0,len(values),8): emit('    .dc '+','.join(f'${v&0xffffff:06x}' for v in values[i:i+8]))
    return '\n'.join(lines)+'\n'


def main():
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('--compiler',default='clang++')
    a=p.parse_args(); exe=build_reference(ROOT/'build/tom-reference',a.compiler)
    for kind in ('lt','ht'):
        controls=json.loads(run([exe,'--tables',kind]).stdout)
        directory=ROOT/'machines'/kind; directory.mkdir(parents=True,exist_ok=True)
        (directory/(kind+'.asm')).write_text(generate(kind,controls))
        manifest=dict(id='org.kitbasher.tr6.'+kind,display_name='TR6 '+('LOW' if kind=='lt' else 'HIGH')+' TOM',
                      category='TR6',short_label=kind.upper(),machine_version='0.1',
                      params=[dict(name='DEC',default=102,transform='raw14'),dict(name='TUNE',default=64,transform='raw14')])
        (directory/(kind+'.json')).write_text(json.dumps(manifest,indent=2)+'\n')
        print(kind,len(state_layout(kind)),'state words')


if __name__=='__main__': main()
