"""Correctness-first Simple606 snare translation; see LICENSE-Simple606.

Audio/filter state is Q20; envelopes Q23; frequency is phase-step times 16.
The synthesis topology is unchanged. Exponentials become recurrences and the
two finite attack curves become lookup tables, not sampled drum waveforms.
"""
import json
import math
from mds_build import ROOT
from generate_bd import word

FS=44100
Q=1<<23
TAU=6.9077553
OUTPUT_GAIN=.5  # The source can exceed full scale; MDS output is signed Q23.
STATE=('active frame duration hold gate gatecoef gateerr gatevalue bodyend '
       'bodyphase ringphase bodyfrac ringfrac basefreq colorratio bend benderr '
       'toneenv tonecoef toneenverr transient transienterr wires wireserr ringrise ringriseerr '
       'snappy body noise rnglo rnghi rngtemp white bp1z1 bp1z2 bp2z1 bp2z2 lp '
       'bp1b0 bp1a1 bp1a2 bp2b0 bp2a1 bp2a2 lpcoef temp1 temp2 attack').split()
assert len(STATE)<=64
S={name:f'x:(r6+${i:x})' for i,name in enumerate(STATE)}


def generate():
    lines=['; GENERATED by tools/generate_sd.py.',
           '; Derived from Simple606 Snare.hpp; see LICENSE-Simple606.',
           '; Unqualified draft: no cold-cache or hardware claim.']
    tables={}
    def emit(*s): lines.extend(s)
    def load(name,reg='a'): emit(f'    move {S[name]},{reg}')
    def save(name,reg='a1'): emit(f'    move {reg},{S[name]}')
    def imm(v,reg='x0'): emit(f'    move #>${word(v):06x},{reg}')
    def mul(v):
        shift=0
        while abs(v)>=1: v/=2; shift+=1
        emit('    move a1,x0'); imm(v,'y0'); emit('    mpy x0,y0,a')
        if shift: emit(f'    asl #{shift},a,a')
    def mulstate(name):
        emit('    move a1,x0'); load(name,'y0'); emit('    mpy x0,y0,a')
    def param(index):
        emit(f'    move y:(r6+${index+1:x}),a','    asr #7,a,a','    and #>$7f,a','    move a1,n0')
    def lookup(label,state):
        emit(f'    move #>{label},r0','    nop','    move p:(r0+n0),x0'); save(state,'x0')
    def decay(name,coef):
        load(name,'x0')
        if isinstance(coef,str): load(coef,'y0')
        else: imm(coef,'y0')
        emit('    mpy x0,y0,a','    clr b'); load(name+'err','b0')
        emit('    add b,a'); save(name+'err','a0'); save(name)
    def sine(phase):
        load(phase); emit('    asr #9,a,a','    and #>$7fff,a','    move a1,r0',
                         '    move x:(r0+>mds_sine),a')
    def advance(phase,fraction):
        load(fraction,'x0'); emit('    add x0,a','    move a1,b','    and #>$f,b'); save(fraction,'b1')
        emit('    asr #4,a,a'); load(phase,'x0'); emit('    add x0,a'); save(phase)
    def bp(prefix):
        load('white'); mulstate(prefix+'b0'); emit('    asl #1,a,a'); save('temp1')
        load(prefix+'z1','x0'); emit('    add x0,a'); save('temp2')
        mulstate(prefix+'a1'); emit('    asl #1,a,a'); load(prefix+'z2','x0')
        emit('    add x0,a'); save(prefix+'z1')
        load('temp2'); mulstate(prefix+'a2'); emit('    asl #1,a,a'); load('temp1','x0')
        emit('    sub x0,a'); save(prefix+'z2'); load('temp2')

    emit('init:','    clr a')
    for name in STATE: save(name)
    emit('    move #>$6063,x0'); save('rnglo','x0'); emit('    rts','trigger:')
    # Filter and oscillator histories reset on a hit; the random stream persists.
    emit('    clr a')
    for name in STATE:
        if name not in ('rnglo','rnghi'): save(name)
    param(0)
    for name in ('duration','hold','gate','gatecoef'): lookup('t_'+name,name)
    param(1)
    for name in ('bodyend','basefreq','tonecoef'): lookup('t_'+name,name)
    param(2); lookup('t_snappy','snappy')
    param(3)
    for name in ('colorratio','bp1b0','bp1a1','bp1a2','bp2b0','bp2a1','bp2a2','lpcoef'):
        lookup('t_'+name,name)
    emit('    move #>$7fffff,x0')
    for name in ('toneenv','transient','wires','ringrise'): save(name,'x0')
    emit(f'    move #>{round(149.23143*(1<<28)/FS)},x0'); save('bend','x0')
    emit(f'    move #>{round(1.1711004/(2*math.pi)*(1<<24))},x0'); save('bodyphase','x0')
    emit(f'    move #>{round((1-1.1/(2*math.pi))*(1<<24))},x0'); save('ringphase','x0')
    emit('    move #>1,x0'); save('active','x0'); emit('    rts','render:')
    load('active'); emit('    tst a','    jeq silent_block','    do #32,block_end')
    load('active'); emit('    tst a','    jeq sample_silent')
    # A single gate is shared by the two additive paths.
    load('frame'); load('hold','x0'); emit('    cmp x0,a','    jlt gate_full')
    load('gate'); mul(1+1.5881701e-5); imm(1.5881701e-5)
    emit('    sub x0,a','    clr b','    tst a','    tlt b,a','    jmp gate_ready',
         'gate_full:','    move #>$7fffff,a','gate_ready:'); save('gatevalue')
    load('frame'); load('bodyend','x0'); emit('    cmp x0,a','    jge body_silent')
    # Analytic attack, sampled only over its finite settling interval.
    load('frame'); emit('    move #>512,x0','    cmp x0,a','    jge attack_full','    move a1,n0')
    lookup('body_attack','attack'); emit('    jmp attack_ready','attack_full:','    move #>$7fffff,x0')
    save('attack','x0'); emit('attack_ready:')
    load('toneenv'); mul(.391); save('temp1')
    load('transient'); mul(.44); load('temp1','x0'); emit('    add x0,a'); mulstate('attack'); save('temp1')
    sine('bodyphase'); mulstate('temp1'); emit('    asr #3,a,a'); save('body')
    load('frame'); emit('    move #>61,x0','    cmp x0,a','    jge impact_done','    move a1,n0')
    lookup('impact','temp1'); load('body'); load('temp1','x0'); emit('    add x0,a'); save('body')
    emit('impact_done:'); load('body'); mul(.710); save('body')
    load('basefreq'); load('bend','x0'); emit('    add x0,a'); advance('bodyphase','bodyfrac')
    emit('    jmp body_ready','body_silent:','    clr a'); save('body'); emit('body_ready:')
    # Exact xorshift32, with Simple606's snare-specific lower-24-bit mapping.
    load('rnglo','x0'); load('rnglo'); emit('    asl #13,a,a','    eor x0,a'); save('rngtemp')
    load('rnglo'); emit('    asr #11,a,a','    and #>$ff,a'); load('rnghi','x0')
    emit('    eor x0,a'); save('rnghi'); load('rnghi')
    emit('    asl #7,a,a','    move a1,x0'); load('rngtemp')
    emit('    asr #17,a,a','    and #>$7f,a','    or x0,a'); load('rngtemp','x0')
    emit('    eor x0,a'); save('rngtemp')
    emit('    asr #19,a,a','    and #>$1f,a','    move a1,x0'); load('rnghi')
    emit('    asl #5,a,a','    or x0,a'); load('rnghi','x0')
    emit('    eor x0,a','    and #>$ff,a'); save('rnghi')
    load('rngtemp'); emit('    asl #5,a,a'); load('rngtemp','x0'); emit('    eor x0,a'); save('rnglo')
    emit('    move #>$800000,x0','    eor x0,a','    move a1,a','    asr #3,a,a'); save('white')
    bp('bp1'); save('noise'); bp('bp2'); mul(-1.597958)
    load('noise','x0'); emit('    add x0,a'); load('lp','x0'); emit('    sub x0,a')
    mulstate('lpcoef'); load('lp','x0'); emit('    add x0,a'); save('lp')
    mulstate('wires'); mul(1.28); save('noise')
    load('frame'); emit('    move #>137,x0','    cmp x0,a','    jge noise_attack_full','    move a1,n0')
    lookup('noise_attack','attack'); emit('    jmp noise_attack_ready','noise_attack_full:','    move #>$7fffff,x0')
    save('attack','x0'); emit('noise_attack_ready:'); load('noise'); mulstate('attack'); save('noise')
    emit('    move #>$7fffff,a'); load('ringrise','x0'); emit('    sub x0,a'); mulstate('wires')
    mul(.014/8); save('temp1'); sine('ringphase'); mulstate('temp1')
    load('noise','x0'); emit('    add x0,a'); mulstate('snappy')
    load('body','x0'); emit('    add x0,a'); mulstate('gatevalue')
    # Q20 -> Q23 with 6 dB output headroom. Comparison removes this known gain.
    emit('    asl #2,a,a','    move a,y:(r7)+')
    # Ring bend follows color, while the shell bend is independent of tune.
    emit(f'    move #>{round(201.09442*(1<<28)/FS)},a'); load('bend','x0'); emit('    add x0,a')
    mulstate('colorratio'); emit('    asl #2,a,a'); advance('ringphase','ringfrac')
    decay('bend',math.exp(-1/(FS*.0133309)))
    decay('toneenv','tonecoef'); decay('transient',math.exp(-TAU/(FS*.030)))
    decay('wires',math.exp(-TAU/(FS*.395))); decay('ringrise',math.exp(-1/(FS*.012)))
    load('frame'); load('hold','x0'); emit('    cmp x0,a','    jlt gate_update_done')
    decay('gate','gatecoef'); emit('gate_update_done:')
    load('frame'); emit('    add #>1,a'); save('frame'); load('duration','x0')
    emit('    cmp x0,a','    jlt sample_done','    clr a'); save('active')
    emit('    jmp sample_done','sample_silent:','    clr a','    move a,y:(r7)+',
         'sample_done:','    nop','block_end:','    rts','silent_block:','    clr a',
         '    do #32,zero_end','    move a,y:(r7)+','zero_end:','    rts')

    for name in ('duration','hold','gate','gatecoef','bodyend','basefreq','tonecoef',
                 'snappy','colorratio','bp1b0','bp1a1','bp1a2','bp2b0','bp2a1','bp2a2','lpcoef'):
        tables['t_'+name]=[]
    for i in range(128):
        d=max(.01,i/127); ratio=2**((-12+24*i/127)/12)
        duration=16323*d; fade=min(duration,16323-duration); hold=duration-fade
        if i==127: hold=16323; fade=0
        values={'duration':math.ceil(duration),'hold':math.ceil(hold),'bodyend':math.ceil(11016/ratio),
                'basefreq':round(201.09442*ratio*(1<<28)/FS),
                'tonecoef':word(math.exp(-TAU*ratio/(FS*.243))),
                'gate':word(math.exp(-11.05*(math.ceil(hold)-hold)/fade) if fade else 1),
                'gatecoef':word(math.exp(-11.05/fade) if fade else 0),
                'snappy':word(i/127),'colorratio':word(ratio/4),
                'lpcoef':word(1-math.exp(-2*math.pi*min(19677.396*ratio,FS*.45)/FS))}
        for prefix,hz,q in (('bp1',2998.628,1.2771896),('bp2',4596.2905,.30369505)):
            w=2*math.pi*hz*ratio/FS; alpha=math.sin(w)/(2*q); norm=1/(1+alpha)
            values[prefix+'b0']=word(.5*math.sin(w)*norm/2)
            values[prefix+'a1']=word(math.cos(w)*norm)
            values[prefix+'a2']=word(-(1-alpha)*norm/2)
        for name,value in values.items(): tables['t_'+name].append(value)
    tables['body_attack']=[word((1-math.exp(-n/(FS*.0007633316)))**3.2748916) for n in range(512)]
    tables['noise_attack']=[word(1-(1-min(n/(FS*.0031),1))**1.3) for n in range(137)]
    tables['impact']=[word(-.3000014*math.exp(-(n/FS-.0002763113)/.0025407782)/8)
                      if .0002763113<=n/FS<.0013649489 else 0 for n in range(61)]
    for name,values in tables.items():
        emit(name+':')
        for i in range(0,len(values),8): emit('    .dc '+','.join(f'${w:06x}' for w in values[i:i+8]))
    return '\n'.join(lines)+'\n'


def main():
    destination=ROOT/'machines/sd'; destination.mkdir(parents=True,exist_ok=True)
    (destination/'sd.asm').write_text(generate())
    manifest=dict(id='org.kitbasher.tr6.sd',display_name='TR6 SNARE',category='TR6',short_label='SD',
                  machine_version='0.1',params=[dict(name=name,default=value,transform='raw14')
                  for name,value in zip(('DEC','TUNE','SNAP','COLR'),(102,64,95,64))])
    (destination/'sd.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(destination)


if __name__=='__main__': main()
