"""Full 47-partial Simple606 CH/OH/CY baseline. See LICENSE-Simple606.

Audio Q19, envelopes Q23, wobble Q26, phases and increments 24+24 bits.
External track storage holds 47 eight-word records; no partials are removed.
"""
import argparse
import json
import math
import os
from pathlib import Path
import re

from mds_build import ROOT
from generate_bd import word
from render_bd import run

Q=1<<23
OUTPUT_GAIN=.5
EXTERNAL_WORDS=47*8
FIELDS={'phase':0,'phasefrac':1,'inch':2,'incl':3,'amp':4,'bell':5,'wobble':6,'wobbleerr':7}
STATE=('active frame duration fade invhi invlo ext '
       'phaselo phasehi wobblelo wobblehi noiselo noisehi rngtemp '
       'whitein whiteout whiteerr outin outout outerr '
       'fastenv fastenverr fastloss slowenv slowenverr slowloss attack attackerr '
       'bell bellerr click clickerr bellgain ratiohi ratiolo basehi baselo '
       'freqhi freqlo ampbase flag taper tonal temp1 temp2 noise envelope f0b0 f0a1 f0a2 f0z1 f0z2 '
       'f1b0 f1a1 f1a2 f1z1 f1z2 tanh_clamps').split()
assert len(STATE)<=64
S={n:f'x:(r6+${i:x})' for i,n in enumerate(STATE)}


def split(value):
    high=math.floor(value*Q)
    low=round((value*Q-high)*Q)
    if low==Q: high+=1; low=0
    assert 0<=high<Q and 0<=low<Q
    return high,low


def build_reference(out,compiler='clang++'):
    out=Path(out).resolve(); out.mkdir(parents=True,exist_ok=True)
    src=ROOT/'.audit-sources/Simple606/Source'
    match=re.search(r'static constexpr SynthDrums606::HiHatSpec kCymbalSpec = \{.*?\n\};',
                    (src/'PluginProcessor.h').read_text(),re.S)
    if not match: raise ValueError('Cymbal specification not found')
    (out/'cymbal_spec.hpp').write_text(match[0]+'\n')
    exe=out/('reference.exe' if os.name=='nt' else 'reference')
    run([compiler,'-std=c++14','-O2','-I',src,'-I',out,ROOT/'tests/metal_reference.cpp','-o',exe])
    return exe


def generate(kind,c,tanh_bits=13,no_wobble=False):
    if not 8<=tanh_bits<=13: raise ValueError('tanh_bits must be 8..13')
    table_shift=23-tanh_bits
    partial_count=len(c['partials'])
    if partial_count not in (3,6,47): raise ValueError('Expected 3, 6 or 47 partials')
    lines=['; GENERATED by tools/generate_metal.py; pinned Simple606 HiHats.hpp.',
           '; See LICENSE-Simple606. Full-path draft, not timing qualified.',
           '; External record: phase, phasefrac, inch, incl, amp, bell, wobble, wobbleerr.']
    if partial_count!=47 or no_wobble:
        lines[1]=f'; See LICENSE-Simple606. Reduced model: {partial_count} partials, wobble={not no_wobble}; not timing qualified.'
    tables={}
    def emit(*s): lines.extend(s)
    def load(n,r='a'): emit(f'    move {S[n]},{r}')
    def save(n,r='a1'): emit(f'    move {r},{S[n]}')
    def extload(n,r='a'): emit(f'    move x:(r2+${FIELDS[n]:x}),{r}')
    def extsave(n,r='a1'): emit(f'    move {r},x:(r2+${FIELDS[n]:x})')
    def imm(v,r='x0'): emit(f'    move #>${word(v):06x},{r}')
    def mul(v):
        shift=0
        while abs(v)>=1: v/=2; shift+=1
        emit('    move a1,x0'); imm(v,'y0'); emit('    mpy x0,y0,a')
        if shift: emit(f'    asl #{shift},a,a')
    def mulstate(n):
        emit('    move a1,x0'); load(n,'y0'); emit('    mpy x0,y0,a')
    def decay(n,loss):
        # 2*(1-pole) preserves the source float32 coefficient's extra bit.
        load(n,'x0')
        if isinstance(loss,str): load(loss,'y0')
        else: imm(loss,'y0')
        emit('    mpy x0,y0,a','    asr #1,a,a','    neg a'); load(n,'b'); load(n+'err','b0')
        emit('    add b,a'); save(n+'err','a0'); save(n)
    def param(i):
        emit(f'    move y:(r6+${i+1:x}),a','    asr #7,a,a','    and #>$7f,a','    move a1,n0')
    def lookup(label,n,values):
        tables[label]=values
        emit(f'    move #>{label},r0','    nop','    move p:(r0+n0),x0'); save(n,'x0')
    def rng(n):
        load(n+'lo','x0'); load(n+'lo'); emit('    asl #13,a,a','    eor x0,a'); save('rngtemp')
        load(n+'lo'); emit('    asr #11,a,a','    and #>$ff,a'); load(n+'hi','x0')
        emit('    eor x0,a'); save(n+'hi'); load(n+'hi'); emit('    asl #7,a,a','    move a1,x0')
        load('rngtemp'); emit('    asr #17,a,a','    and #>$7f,a','    or x0,a'); load('rngtemp','x0')
        emit('    eor x0,a'); save('rngtemp')
        emit('    asr #19,a,a','    and #>$1f,a','    move a1,x0'); load(n+'hi')
        emit('    asl #5,a,a','    or x0,a'); load(n+'hi','x0'); emit('    eor x0,a','    and #>$ff,a'); save(n+'hi')
        load('rngtemp'); emit('    asl #5,a,a'); load('rngtemp','x0'); emit('    eor x0,a'); save(n+'lo')
        emit('    asr #8,a,a','    and #>$ffff,a','    move a1,x0'); load(n+'hi')
        emit('    asl #16,a,a','    or x0,a','    move #>$800000,x0','    eor x0,a','    move a1,a')
    def dc(n):
        load(n+'in','x0'); save(n+'in'); emit('    sub x0,a'); save('temp1')
        load(n+'out'); mul(.995); emit('    clr b'); load(n+'err','b0')
        emit('    add b,a'); save(n+'err','a0'); load('temp1','x0'); emit('    add x0,a'); save(n+'out')
    def filt(i):
        n=f'f{i}'; mulstate(n+'b0'); emit('    asl #1,a,a'); save('temp1')
        load(n+'z1','x0'); emit('    add x0,a'); save('temp2')
        mulstate(n+'a1'); emit('    asl #1,a,a'); load(n+'z2','x0'); emit('    add x0,a')
        load('temp1','x0'); op='sub' if i==0 else 'add'
        emit(f'    {op} x0,a',f'    {op} x0,a'); save(n+'z1')
        load('temp2'); mulstate(n+'a2'); emit('    asl #1,a,a'); load('temp1','x0')
        emit('    add x0,a'); save(n+'z2'); load('temp2')

    emit('init:','    clr a')
    for n in STATE: save(n)
    seed={'ch':0x606606,'oh':0x606607,'cy':0x606608}[kind]
    for n,salt in [('phase',0x9e3779b9),('wobble',0x51d3b7a1),('noise',0xa511e9b3)]:
        val=seed^salt
        emit(f'    move #>${val&0xffffff:06x},x0'); save(n+'lo','x0')
        emit(f'    move #>${val>>24:06x},x0'); save(n+'hi','x0')
    emit('    move r1,a','    asl #9,a,a','    tfr a,b','    asl #1,a,a','    add b,a',
         '    add #>mds_track,a'); save('ext')
    emit('    move a1,r2','    move #>$ffffff,m2','    clr a',f'    do #{partial_count*8},init_clear_end',
         '    move a,x:(r2)+','init_clear_end:','    rts','trigger:','    clr a')
    preserved={'ext','phaselo','phasehi','wobblelo','wobblehi','noiselo','noisehi','whitein','whiteout','whiteerr','tanh_clamps'}
    for n in STATE:
        if n not in preserved: save(n)
    emit('    move #>$ffffff,m2','    move #>$ffffff,m3')
    param(0)
    for n in ('duration','fade'): lookup('t_'+n,n,[r[n] for r in c['decay']])
    for j,n in enumerate(('invhi','invlo')): lookup('t_'+n,n,[split(r['inverse'])[j] for r in c['decay']])
    for n in ('fast','slow'): lookup('t_'+n+'loss',n+'loss',[word(2*(1-r[n])) for r in c['decay']])
    param(1)
    for j,n in enumerate(('ratiohi','ratiolo')): lookup('t_'+n,n,[split(r['ratio']/4)[j] for r in c['pitch']])
    for i in range(2):
        for j,n in enumerate(('b0','a1','a2')):
            lookup(f't_f{i}{n}',f'f{i}{n}',[word(r['filters'][i][j]*(.5 if j==0 else -.5)) for r in c['pitch']])
    emit('    move #>$7fffff,x0')
    for n in ('fastenv','slowenv','attack','bell','click'): save(n,'x0')
    load('ext','r2'); emit('    move #>partials,r3','    move #>8,n2',f'    do #{partial_count},trigger_partials_end')
    rng('phase'); mul(.3); imm(.3); emit('    add x0,a'); extsave('phase')
    emit('    clr a')
    for n in ('phasefrac','wobble','wobbleerr'): extsave(n)
    for n in ('basehi','baselo','ampbase','flag'):
        emit('    move p:(r3)+,x0'); save(n,'x0')
    load('basehi','x0'); load('ratiohi','y0'); emit('    mpy x0,y0,a')
    load('ratiolo','y0'); emit('    mpy x0,y0,b','    asr #23,b,b','    add b,a')
    load('baselo','x0'); load('ratiohi','y0'); emit('    mpy x0,y0,b','    asr #23,b,b','    add b,a','    asl #2,a,a')
    save('freqhi'); save('freqlo','a0'); imm(.48); emit('    cmp x0,a','    jge muted_partial')
    emit('    asl #1,a,a'); extsave('inch'); extsave('incl','a0')
    load('freqhi'); imm(.4); emit('    cmp x0,a','    jle full_partial')
    imm(.48); emit('    neg a','    add x0,a'); mul(12.5); save('taper')
    mulstate('taper'); save('temp1'); load('taper'); mul(-.5); imm(.75); emit('    add x0,a')
    mulstate('temp1'); emit('    asl #2,a,a'); mulstate('ampbase'); extsave('amp'); emit('    jmp partial_ready',
        'full_partial:'); load('ampbase'); extsave('amp'); emit('    jmp partial_ready','muted_partial:','    clr a')
    for n in ('inch','incl','amp'): extsave(n)
    emit('partial_ready:'); load('flag'); extsave('bell')
    emit('    move (r2)+n2','    nop','trigger_partials_end:','    move #>1,x0'); save('active','x0')
    emit('    rts','render:'); load('active'); emit('    tst a','    jeq silent_block','    move #>8,n2','    do #32,block_end')
    load('active'); emit('    tst a','    jeq sample_silent')
    load('bell'); mul(c['bell_amount']/2); imm(.5); emit('    add x0,a'); save('bellgain')
    decay('bell',2*(1-c['bell'])); emit('    clr a'); save('tonal'); load('ext','r2')
    emit(f'    do #{partial_count},render_partials_end')
    if not no_wobble:
        rng('wobble'); mul(c['wobble_drive']*1024); emit('    asr #7,a,a'); save('temp1'); save('temp2','a0')
        extload('wobble','x0'); imm(c['wobble_alpha']*128,'y0'); emit('    mpy x0,y0,a','    asr #7,a,a','    neg a')
        extload('wobble','b'); extload('wobbleerr','b0'); emit('    add b,a'); load('temp1','b'); load('temp2','b0')
        emit('    add b,a'); extsave('wobble'); extsave('wobbleerr','a0')
    extload('phase'); emit('    asr #9,a,a','    and #>$7fff,a','    move a1,r0','    move x:(r0+>mds_sine),x0')
    extload('amp','y0'); emit('    mpy x0,y0,a','    asr #2,a,a'); save('temp1')
    extload('bell'); emit('    tst a','    jeq no_bell_accent'); load('temp1'); mulstate('bellgain'); emit('    asl #1,a,a'); save('temp1')
    emit('no_bell_accent:'); load('tonal'); load('temp1','x0'); emit('    add x0,a'); save('tonal')
    if not no_wobble:
        extload('inch','x0'); extload('wobble','y0'); emit('    mpy x0,y0,a','    asr #3,a,a')
        extload('inch','b'); extload('incl','b0'); emit('    add b,a')
    else:
        extload('inch'); extload('incl','a0')
    extload('phase','b'); extload('phasefrac','b0'); emit('    add b,a'); extsave('phase'); extsave('phasefrac','a0')
    emit('    move (r2)+n2','    nop','render_partials_end:')
    rng('noise'); emit('    asr #4,a,a'); dc('white'); filt(0); filt(1); save('noise')
    decay('attack',2*c['attack']); decay('fastenv','fastloss'); decay('slowenv','slowloss')
    load('fastenv'); mul(c['fast_weight']); save('temp1'); load('slowenv'); mul(1-c['fast_weight'])
    load('temp1','x0'); emit('    add x0,a'); save('envelope')
    emit('    move #>$7fffff,a'); load('attack','x0'); emit('    sub x0,a'); mulstate('envelope'); save('envelope')
    load('duration'); load('frame','x0'); emit('    sub x0,a'); load('fade','x0'); emit('    cmp x0,a','    jge gate_ready')
    emit('    move a1,x0'); load('invhi','y0'); emit('    mpy x0,y0,a','    asl #23,a,a')
    load('invlo','y0'); emit('    mpy x0,y0,b','    add b,a'); mulstate('envelope'); save('envelope')
    emit('gate_ready:'); load('tonal'); mul(c['tonal_mix']); save('temp1'); load('noise'); mul(c['noise_mix'])
    load('temp1','x0'); emit('    add x0,a'); mul(c['drive'])
    # Interpolated tanh over [-8,8], Q19. Count any range clamp explicitly.
    emit('    move #>$3fffff,x0','    cmp x0,a','    jgt tanh_high','    move #>$c00000,x0','    cmp x0,a','    jlt tanh_low','    jmp tanh_ready',
         'tanh_high:','    move #>$3fffff,a','    jmp tanh_clamped','tanh_low:','    move #>$c00000,a',
         'tanh_clamped:'); save('temp1'); load('tanh_clamps'); emit('    add #>1,a'); save('tanh_clamps'); load('temp1')
    emit('tanh_ready:','    move a1,b',f'    and #>${(1<<table_shift)-1:x},b',f'    asl #{23-table_shift},b,b','    move b1,y1',
         f'    asr #{table_shift},a,a',f'    add #>${1<<(tanh_bits-1):x},a','    move a1,n0','    move #>tanh_table,r0','    nop',
         '    move p:(r0+n0),x0','    move #>tanh_table+1,r0','    nop','    move p:(r0+n0),a',
         '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a')
    mulstate('envelope'); save('tonal'); load('noise'); mul(c['click_amount']); mulstate('click')
    load('tonal','x0'); emit('    add x0,a'); mul(c['trim']); dc('out')
    emit('    asl #3,a,a','    move a,y:(r7)+'); decay('click',2*(1-c['click']))
    load('frame'); emit('    add #>1,a'); save('frame'); load('duration','x0')
    emit('    cmp x0,a','    jlt sample_done','    clr a'); save('active')
    emit('    jmp sample_done','sample_silent:','    clr a','    move a,y:(r7)+','sample_done:','    nop',
         'block_end:','    rts','silent_block:','    clr a','    do #32,zero_end','    move a,y:(r7)+','zero_end:','    rts')
    partials=[]
    for freq,amp,bell in c['partials']: partials += [*split(freq/44100),word(amp/4),int(bell)]
    tables['partials']=partials
    tables['tanh_table']=[word(math.tanh((i-(1<<(tanh_bits-1)))/(1<<(tanh_bits-4)))/16) for i in range((1<<tanh_bits)+1)]
    for label,values in tables.items():
        emit(label+':')
        for i in range(0,len(values),8): emit('    .dc '+','.join(f'${v&0xffffff:06x}' for v in values[i:i+8]))
    return '\n'.join(lines)+'\n'


def main():
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('--compiler',default='clang++')
    a=p.parse_args(); exe=build_reference(ROOT/'build/metal-reference',a.compiler)
    for kind in ('ch','oh','cy'):
        controls=json.loads(run([exe,'--tables',kind]).stdout)
        directory=ROOT/'machines'/kind; directory.mkdir(parents=True,exist_ok=True)
        (directory/(kind+'.asm')).write_text(generate(kind,controls))
        manifest=dict(id='org.kitbasher.tr6.'+kind,display_name='TR6 '+{'ch':'CLOSED HAT','oh':'OPEN HAT','cy':'CYMBAL'}[kind],
                      category='TR6',short_label=kind.upper(),machine_version='0.1',
                      params=[dict(name='DEC',default=102 if kind=='cy' else 89,transform='raw14'),dict(name='TUNE',default=64,transform='raw14')])
        (directory/(kind+'.json')).write_text(json.dumps(manifest,indent=2)+'\n')
        print(kind,len(STATE),'local words,',EXTERNAL_WORDS,'external words')


if __name__=='__main__': main()
