"""Full-path Simple606 CP draft generator. See LICENSE-Simple606."""
import argparse
import json
import math
import os
from pathlib import Path

from mds_build import ROOT
from render_bd import run
from generate_bd import word

Q=1<<23
OUTPUT_GAIN=.5
EXTERNAL_WORDS=1472
STATE=('active frame duration core_frame generated center fraction step direct ext taps histpos '
       'noiselo noisehi rngtemp gausssum time timefrac dthi dtlo invdecay decay spread invdiff noisegain '
       'colorstep colorfrac colorpos colorindex colorbase norm dst p0 p1 p2 p3 poly t t2 t3 '
       'opening handoff fast late openingerr handofferr fasterr lateerr '
       'full dry fullerr dryerr sampleindex mix target gateattack envelope terminal '
       'tmp1 tmp2 tmp3 fade calibrated drysat residual hpinput hpoutput hperr lateweight '
       'tanh_clamps color_clamps').split()
assert len(STATE)<=119
S={n:(f'x:(r6+${i:x})' if i<64 else f'y:(r6+${i-64+9:x})') for i,n in enumerate(STATE)}


def generate(c):
    lines=['; GENERATED by tools/generate_clap.py; pinned Simple606 Clap.hpp.',
           '; See LICENSE-Simple606. Full-path draft, not timing qualified.',
           '; Audio Q18; FIR coefficients Q23; polynomial Q21; time Q24+24.',
           '; External: 4x192 coefficients, 192 noise history, 256x2 core frames.']
    tables={}
    def emit(*s): lines.extend(s)
    def load(n,r='a'): emit(f'    move {S[n]},{r}')
    def save(n,r='a1'): emit(f'    move {r},{S[n]}')
    def imm(v,r='x0'): emit(f'    move #>${word(v):06x},{r}')
    def mul(v):
        shift=0
        while abs(v)>=1: v/=2; shift+=1
        emit('    move a1,x0'); imm(v,'y0'); emit('    mpy x0,y0,a')
        if shift: emit(f'    asl #{shift},a,a')
    def mulstate(n):
        emit('    move a1,x0'); load(n,'y0'); emit('    mpy x0,y0,a')
    def add(n): load(n,'x0'); emit('    add x0,a')
    def sub(n): load(n,'x0'); emit('    sub x0,a')
    def param(i): emit(f'    move y:(r6+${i+1:x}),a','    asr #7,a,a','    and #>$7f,a','    move a1,n0')
    def lookup(label,n,values):
        tables[label]=values
        emit(f'    move #>{label},r0','    nop','    move p:(r0+n0),x0'); save(n,'x0')
    def address(offset,r='r2'):
        load('ext'); emit(f'    add #>{offset},a',f'    move a1,{r}')
    def clockadd():
        load('time'); load('timefrac','a0'); load('dthi','b'); load('dtlo','b0')
        emit('    add b,a'); save('time'); save('timefrac','a0')
    def ramp(time,start,end,label):
        load(time); imm(start*2); emit('    sub x0,a','    tst a',f'    jle {label}_zero')
        imm(2*(end-start)); emit('    cmp x0,a',f'    jge {label}_one')
        mul(1/(2*(end-start))); emit('    jsr cosine_ramp',f'    jmp {label}_done',label+'_zero:','    clr a',f'    jmp {label}_done',
            label+'_one:','    move #>$7fffff,a',label+'_done:')
    def gate(label,onset,attack,hold,t60,level,diffuse=False):
        emit(label+':'); load('time'); imm(onset*2); emit('    sub x0,a','    tst a',f'    jlt {label}_zero')
        if attack:
            # Clamp age before multiplying: a late sample divided by a very
            # short attack can overflow even the extended DSP accumulator.
            imm(2*attack); emit('    cmp x0,a',f'    jge {label}_attack_one')
            mul(1/(2*attack)); emit('    jsr cosine_ramp',f'    jmp {label}_attack_ready',label+'_attack_one:','    move #>$7fffff,a',label+'_attack_ready:')
        else: emit('    move #>$7fffff,a')
        save('gateattack')
        load('time'); imm(2*(onset+attack+hold)); emit('    sub x0,a','    tst a',f'    jge {label}_age','    clr a',label+'_age:')
        mulstate('invdecay')
        if diffuse: mulstate('invdiff')
        mul(6.907755278982137/(2*t60)); imm(1); emit('    cmp x0,a',f'    jge {label}_zero','    jsr exponential')
        mulstate('gateattack'); mul(level/4)
        if label in ('foundation','floor'): mulstate('decay')
        emit('    rts',label+'_zero:','    clr a','    rts')

    emit('init:','    clr a')
    for n in STATE: save(n)
    emit('    move #>$06c1a9,x0'); save('noiselo','x0')
    emit('    move #>$06,x0'); save('noisehi','x0')
    emit('    move r1,a','    asl #9,a,a','    tfr a,b','    asl #1,a,a','    add b,a','    add #>mds_track,a'); save('ext')
    emit('    move a1,r2','    move #>$ffffff,m2','    clr a',f'    do #{EXTERNAL_WORDS},init_clear_end','    move a,x:(r2)+','init_clear_end:','    rts')
    emit('trigger:','    clr a')
    for n in STATE:
        if n not in ('ext','noiselo','noisehi','tanh_clamps','color_clamps'): save(n)
    for i in range(6): emit(f'    move #>$ffffff,m{i}')
    address(0); emit('    clr a',f'    do #{EXTERNAL_WORDS},trigger_clear_end','    move a,x:(r2)+','trigger_clear_end:')
    emit(f'    move #>{c["duration"]},x0'); save('duration','x0')
    param(0)
    lookup('t_decay','decay',[word(v) for v in c['decay']])
    lookup('t_invdecay','invdecay',[word(1/(32*v)) for v in c['decay']])
    param(2)
    lookup('t_noisegain','noisegain',[word(v[0]) for v in c['noise']])
    lookup('t_spread','spread',[word(v[1]) for v in c['noise']])
    lookup('t_invdiff','invdiff',[word(1/(1+.45*v[1])) for v in c['noise']])
    param(1)
    lookup('t_taps','taps',[r['taps'] for r in c['pitch']])
    lookup('t_direct','direct',[int(r['core_step']==1) for r in c['pitch']])
    lookup('t_step','step',[round(r['core_step']*(1<<24))&0xffffff for r in c['pitch']])
    dt=[round(2/r['core_rate']*(1<<47)) for r in c['pitch']]
    lookup('t_dthi','dthi',[v>>24 for v in dt]); lookup('t_dtlo','dtlo',[v&0xffffff for v in dt])
    lookup('t_colorstep','colorstep',[math.floor(r['color_step']) for r in c['pitch']])
    lookup('t_colorfrac','colorfrac',[round((r['color_step']%1)*(1<<24)) for r in c['pitch']])
    for i in range(4):
        lookup(f't_norm{i}','norm',[word(r['scale'][i]/2) for r in c['pitch']])
        emit(f'    move #>color{i},x0'); save('colorbase','x0')
        address(i*192); save('dst')
        emit('    jsr configure_color')
        # configure_color clobbers n0; reload the selected knob.
        if i!=3: param(1)
    emit('    do #192,prewarm_end','    jsr gaussian','    jsr push_noise','    nop','prewarm_end:',
         '    move #>1,x0'); save('active','x0'); emit('    rts')

    emit('configure_color:','    clr a'); save('colorpos'); save('colorindex')
    load('dst','r2'); load('taps','x0'); emit('    do x0,configure_end')
    load('colorindex'); add('colorbase'); emit('    move a1,r0','    nop')
    for n in ('p0','p1','p2','p3'): emit('    move p:(r0)+,x0'); save(n,'x0')
    emit('    clr a'); load('colorpos','a1'); emit('    asr #1,a,a'); save('t')
    mulstate('t'); save('t2'); mulstate('t'); save('t3')
    load('p0'); emit('    neg a'); load('p1','x0'); emit('    add x0,a','    add x0,a','    add x0,a')
    load('p2','x0'); emit('    sub x0,a','    sub x0,a','    sub x0,a'); add('p3'); mulstate('t3'); save('poly')
    load('p0'); emit('    asl #1,a,a'); load('p1','x0')
    for _ in range(5): emit('    sub x0,a')
    load('p2','x0')
    for _ in range(4): emit('    add x0,a')
    sub('p3'); mulstate('t2'); add('poly'); save('poly')
    load('p2'); sub('p0'); mulstate('t'); add('poly'); add('p1'); add('p1')
    # Base values Q21; cubic has factor 1/2 and norm is scale/2:
    # their factors cancel, leaving a two-bit shift to Q23.
    mulstate('norm'); emit('    asl #2,a,a','    move a,x:(r2)+')
    emit('    clr a'); load('colorpos','a1'); emit('    clr b'); load('colorfrac','b1')
    emit('    add b,a'); save('colorpos'); emit('    asr #24,a,a'); add('colorstep'); add('colorindex'); save('colorindex')
    emit('    nop','configure_end:','    rts')

    emit('gaussian:','    clr a'); save('gausssum')
    emit('    do #6,gaussian_end','    jsr random','    asr #3,a,a'); add('gausssum'); save('gausssum')
    emit('    nop','gaussian_end:'); load('gausssum'); mul(math.sqrt(.5)/4); emit('    rts')
    emit('random:')
    load('noiselo','x0'); load('noiselo'); emit('    asl #13,a,a','    eor x0,a'); save('rngtemp')
    load('noiselo'); emit('    asr #11,a,a','    and #>$ff,a'); load('noisehi','x0'); emit('    eor x0,a'); save('noisehi')
    load('noisehi'); emit('    asl #7,a,a','    move a1,x0'); load('rngtemp')
    emit('    asr #17,a,a','    and #>$7f,a','    or x0,a'); load('rngtemp','x0'); emit('    eor x0,a'); save('rngtemp')
    emit('    asr #19,a,a','    and #>$1f,a','    move a1,x0'); load('noisehi'); emit('    asl #5,a,a','    or x0,a')
    load('noisehi','x0'); emit('    eor x0,a','    and #>$ff,a'); save('noisehi')
    load('rngtemp'); emit('    asl #5,a,a'); load('rngtemp','x0'); emit('    eor x0,a'); save('noiselo')
    emit('    asr #8,a,a','    and #>$ffff,a','    move a1,x0'); load('noisehi')
    emit('    asl #16,a,a','    or x0,a','    move #>$800000,x0','    eor x0,a','    move a1,a','    rts')
    emit('push_noise:'); save('tmp1'); address(768); add('histpos'); emit('    move a1,r2'); load('tmp1')
    emit('    move a,x:(r2)'); load('histpos'); emit('    add #>1,a'); load('taps','x0')
    emit('    cmp x0,a','    jlt push_ready','    clr a','push_ready:'); save('histpos'); emit('    rts')

    emit('core:','    jsr gaussian','    jsr push_noise','    clr a')
    for n in ('opening','handoff','fast','late','openingerr','handofferr','fasterr','lateerr'): save(n)
    for i in range(4): address(i*192,f'r{i}')
    address(768,'r5'); add('histpos'); emit('    sub #>1,a','    move a1,r4')
    load('taps','x0'); emit('    do x0,fir_end','    move r4,a','    move r5,x0','    cmp x0,a','    jge fir_index_ready')
    add('taps'); emit('    move a1,r4','fir_index_ready:','    move x:(r4)-,y0')
    for i,n in enumerate(('opening','handoff','fast','late')):
        emit(f'    move x:(r{i})+,x0','    mpy x0,y0,a'); load(n,'b'); load(n+'err','b0')
        emit('    add b,a'); save(n); save(n+'err','a0')
    emit('    nop','fir_end:','    clr a'); save('envelope')
    for i in range(4): emit(f'    jsr burst{i}'); add('envelope'); save('envelope')
    emit('    jsr snap'); add('envelope'); mulstate('opening'); emit('    asl #2,a,a'); save('dry'); save('full')
    emit('    jsr terminal_fast'); save('terminal'); emit('    jsr terminal_slow'); add('terminal'); save('terminal')
    ramp('time',.055,.080,'fast_ramp'); save('mix')
    load('fast'); sub('handoff'); mulstate('mix'); add('handoff'); save('tmp3')
    ramp('time',.110,.170,'late_ramp'); save('mix')
    load('late'); sub('tmp3'); mulstate('mix'); add('tmp3'); mulstate('terminal'); emit('    asl #2,a,a'); add('full'); save('full')
    emit('    jsr foundation'); save('envelope'); emit('    jsr floor'); add('envelope'); mulstate('late'); emit('    asl #2,a,a'); add('full'); save('full')
    clockadd(); load('core_frame'); emit('    add #>1,a'); save('core_frame'); emit('    rts')

    emit('upsample:'); load('center'); emit('    add #>64,a'); save('target')
    emit('generate_next:'); load('core_frame'); load('target','x0'); emit('    cmp x0,a','    jgt generate_ready','    jsr core')
    load('core_frame'); emit('    sub #>1,a','    and #>$ff,a','    asl #1,a,a'); add('ext'); emit('    add #>960,a','    move a1,r2')
    load('full'); emit('    move a,x:(r2)+'); load('dry'); emit('    move a,x:(r2)'); load('core_frame'); save('generated')
    emit('    jmp generate_next','generate_ready:','    clr a')
    for n in ('full','dry','fullerr','dryerr'): save(n)
    # Discard the shifted-out fraction before multiplying the integer phase by
    # 128. Leaving A0 live would turn sub-phase bits into a table-address offset.
    emit('    clr a'); load('fraction','a1'); emit('    asr #19,a,a','    move a1,a','    asl #7,a,a','    add #>reconstruction,a','    move a1,r0','    add #>128,a','    move a1,r1')
    load('fraction'); emit('    and #>$7ffff,a','    asl #4,a,a'); save('mix')
    load('center'); emit('    sub #>63,a'); save('sampleindex')
    emit('    do #128,reconstruct_end','    move p:(r0)+,x0','    move p:(r1)+,a','    sub x0,a'); save('tmp1','x0')
    mulstate('mix'); add('tmp1'); save('tmp2')
    load('sampleindex'); emit('    tst a','    jlt reconstruct_skip','    and #>$ff,a','    asl #1,a,a'); add('ext')
    emit('    add #>960,a','    move a1,r2','    nop')
    for n in ('full','dry'):
        emit('    move x:(r2)+,x0'); load('tmp2','y0'); emit('    mpy x0,y0,a'); load(n,'b'); load(n+'err','b0')
        emit('    add b,a'); save(n); save(n+'err','a0')
    emit('reconstruct_skip:'); load('sampleindex'); emit('    add #>1,a'); save('sampleindex')
    emit('    nop','reconstruct_end:','    clr a'); load('fraction','a1'); emit('    clr b'); load('step','b1')
    emit('    add b,a'); save('fraction'); emit('    asr #24,a,a'); add('center'); save('center'); emit('    rts')

    emit('render:'); load('active'); emit('    tst a','    jeq silent_block','    do #32,block_end')
    load('active'); emit('    tst a','    jeq sample_silent'); load('direct'); emit('    tst a','    jeq resampled','    jsr core','    jmp raw_ready','resampled:','    jsr upsample','raw_ready:')
    # Output time is independent of core time and represented as Q24.
    load('frame'); mul(16384/44100); emit('    asl #10,a,a'); save('tmp3')
    ramp('tmp3',.290,.301,'fade_ramp'); emit('    neg a','    add #>$7fffff,a'); save('fade')
    mulstate('fade'); save('fade'); mulstate('fade'); save('fade')
    load('full'); mulstate('fade'); mul(1/3); emit('    jsr tanh'); mul(3); save('calibrated')
    load('dry'); mulstate('fade'); mul(1/3); emit('    jsr tanh'); mul(3); save('drysat')
    load('calibrated'); sub('drysat'); save('residual'); load('spread'); emit('    tst a','    jeq noise_left')
    load('hpoutput'); add('residual'); sub('hpinput'); mul(c['air_hp']); emit('    clr b'); load('hperr','b0'); emit('    add b,a')
    save('hpoutput'); save('hperr','a0'); load('residual'); save('hpinput')
    ramp('tmp3',.045,.170,'air_ramp'); save('lateweight')
    mul(.60); imm(.40); emit('    add x0,a'); mulstate('spread'); mulstate('residual'); add('calibrated'); save('calibrated')
    load('residual'); mul(2/.75); emit('    jsr tanh'); mul(.75); save('tmp1')
    load('lateweight'); mul(.55); imm(.20); emit('    add x0,a'); mulstate('spread'); mulstate('tmp1'); add('calibrated'); save('calibrated')
    load('lateweight'); mul(.50); imm(.15); emit('    add x0,a'); mulstate('spread'); mulstate('hpoutput'); add('calibrated')
    emit('    jmp output_ready','noise_left:'); load('residual'); mulstate('noisegain'); add('drysat')
    emit('output_ready:'); mul(.1793169072680733*OUTPUT_GAIN); emit('    asl #5,a,a','    move a,y:(r7)+')
    load('frame'); emit('    add #>1,a'); save('frame'); load('duration','x0'); emit('    cmp x0,a','    jlt sample_done','    clr a'); save('active')
    emit('    jmp sample_done','sample_silent:','    clr a','    move a,y:(r7)+','sample_done:','    nop','block_end:','    rts',
         'silent_block:','    clr a','    do #32,zero_end','    move a,y:(r7)+','zero_end:','    rts')

    # cos(pi*x) = sine(quarter_cycle + half_cycle*x), x is Q23.
    emit('cosine_ramp:','    add #>$400000,a','    asr #9,a,a','    and #>$7fff,a','    move a1,r0',
         '    move x:(r0+>mds_sine),a','    neg a','    add #>$7fffff,a','    asr #1,a,a','    rts')
    emit('exponential:','    move a1,b','    and #>$fff,b','    asl #11,b,b','    move b1,y1',
         '    asr #12,a,a','    move a1,n0','    move #>exp_table,r0','    nop',
         '    move p:(r0+n0),x0','    move #>exp_table+1,r0','    nop','    move p:(r0+n0),a',
         '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a','    rts')
    # Q18 tanh input/output, +/-8 at 1/128 resolution. Clamps are audited.
    emit('tanh:','    move #>$1fffff,x0','    cmp x0,a','    jgt tanh_high','    move #>$e00000,x0',
         '    cmp x0,a','    jlt tanh_low','    jmp tanh_ready','tanh_high:','    move #>$1fffff,a','    jmp tanh_clamped',
         'tanh_low:','    move #>$e00000,a','tanh_clamped:'); save('tmp2'); load('tanh_clamps'); emit('    add #>1,a'); save('tanh_clamps'); load('tmp2')
    emit('tanh_ready:','    move a1,b','    and #>$7ff,b','    asl #12,b,b','    move b1,y1',
         '    asr #11,a,a','    add #>1024,a','    move a1,n0','    move #>tanh_table,r0','    nop',
         '    move p:(r0+n0),x0','    move #>tanh_table+1,r0','    nop','    move p:(r0+n0),a',
         '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a','    rts')
    for i,(onset,t60,level) in enumerate(zip((0,.010737,.021735,.032778),(.0125,.014,.019,.025),(2,1.85,1.16,.46))):
        gate(f'burst{i}',onset,0 if i==0 else .00016,.00030,t60,level)
    gate('snap',.032778,.00012,.00035,.025,.55)
    gate('terminal_fast',.03278,.00020,.019,.225,.72*.955,True)
    gate('terminal_slow',.03278,.00020,.019,.890,.72*.045,True)
    gate('foundation',.165,.020,0,.760,.022,True)
    gate('floor',.250,.015,0,.760,.004,True)
    for i,values in enumerate(c['colors']): tables[f'color{i}']=[0]+[word(v/4) for v in values]+[0,0]
    tables['reconstruction']=[word(v) for row in c['reconstruction'] for v in row]
    tables['exp_table']=[word(math.exp(-i/64)) for i in range(2049)]
    tables['tanh_table']=[word(math.tanh((i-1024)/128)/32) for i in range(2049)]
    for label,values in tables.items():
        emit(label+':')
        for i in range(0,len(values),8): emit('    .dc '+','.join(f'${v&0xffffff:06x}' for v in values[i:i+8]))
    return '\n'.join(lines)+'\n'


def build_reference(out,compiler='clang++'):
    out=Path(out).resolve(); out.mkdir(parents=True,exist_ok=True)
    src=ROOT/'.audit-sources/Simple606/Source'
    exe=out/('reference.exe' if os.name=='nt' else 'reference')
    run([compiler,'-std=c++14','-O2','-I',src,ROOT/'tests/clap_reference.cpp','-o',exe])
    return exe


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--compiler',default='clang++')
    p.add_argument('--out',type=Path,default=ROOT/'build/cp-reference')
    a=p.parse_args(); exe=build_reference(a.out,a.compiler)
    controls=json.loads(run([exe,'--tables']).stdout)
    (a.out/'controls.json').write_text(json.dumps(controls,indent=2)+'\n')
    source=generate(controls)
    (a.out/'cp.asm').write_text(source)
    directory=ROOT/'machines/cp'; directory.mkdir(parents=True,exist_ok=True)
    (directory/'cp.asm').write_text(source)
