"""Generate a correctness-first fixed-point translation of Simple606 BassDrum.

Derived signal path: Copyright (c) 2026 Matthew Fecher (MIT; see LICENSE-Simple606).
Audio/filter state is Q21 (actual audio / 4 in DSP fractional arithmetic).
Envelope state is Q23, body amplitude is stored divided by two, phase wraps at
2^24. Lookup tables translate the source's trigger math; they are not samples.
This initial implementation floors modulated controls to their 7-bit setting.
"""
import json
import math
import re
from pathlib import Path
from mds_build import ROOT

Q = 1 << 23
FS = 44100
STATE = 'active phase freq target pitch amp ampcoef clickenv clickcoef impenv impcoef clickgain impgain bodylp clicklp implp z1 z2 lastbody rnglo rnghi noisein noiseout dcin dcout silent body click delta rngtemp temp heatgain heatnorm phasefrac freqerr amperr clickenverr impenverr dcerr'.split()
CONTROL_STATE = ['ampnext','clickenvnext','impenvnext','freqnext']
STRIDE_STATE = ['upsample']
S = {name: f'x:(r6+${i:x})' for i,name in enumerate(STATE+CONTROL_STATE+STRIDE_STATE)}


def state_layout(control_rate=1,render_stride=1):
    if render_stride not in (1,2) or (render_stride==2 and control_rate!=32):
        raise ValueError('Stride 2 state requires 32 output-frame controls')
    return STATE+(CONTROL_STATE if control_rate!=1 else [])+(STRIDE_STATE if render_stride!=1 else [])


def word(value):
    n = round(value*Q)
    if not -Q <= n <= Q:
        raise ValueError(f'Fraction out of range: {value}')
    return min(Q-1,n) & 0xffffff


def generate(tanh_bits=13,resident_state=False,lcg_noise=False,seed=None,control_rate=1,simple_impulse=False,omit_impulse=False,sequential_tanh=False,quadratic_saturation=False,recursive_body=False,lean_mix=False,bounded_activity=False,scheduled_mix=False,rounded_dc=False,linear_base=False,linear_base_gain=1.0,tail_elision=False,render_stride=1):
    if not 8<=tanh_bits<=13: raise ValueError('tanh_bits must be 8..13')
    if seed is not None and not 0<=seed<=0xffffffff: raise ValueError('seed must fit uint32')
    if control_rate not in (1,16,32): raise ValueError('control_rate must be 1, 16 or 32')
    if control_rate!=1 and not resident_state: raise ValueError('Control interpolation requires resident state')
    if simple_impulse and omit_impulse: raise ValueError('Choose simple or omitted impulse, not both')
    if quadratic_saturation and (not omit_impulse or sequential_tanh):
        raise ValueError('Quadratic saturation requires omitted impulse and excludes sequential tanh')
    if recursive_body and (not omit_impulse or control_rate!=32):
        raise ValueError('Recursive body requires omitted impulse and 32-sample control endpoints')
    if lean_mix and not (recursive_body and lcg_noise):
        raise ValueError('Lean mix requires recursive body and LCG noise')
    if bounded_activity and not lean_mix:
        raise ValueError('Bounded activity requires lean mix')
    if scheduled_mix and not (lean_mix and (quadratic_saturation or sequential_tanh)):
        raise ValueError('Scheduled mix requires lean mix and quadratic or sequential saturation')
    if (rounded_dc or linear_base) and not scheduled_mix:
        raise ValueError('Rounded DC and linear base require scheduled mix')
    if not math.isfinite(linear_base_gain) or not 0<linear_base_gain<=1 or (linear_base_gain!=1 and not linear_base):
        raise ValueError('Linear base gain must be in (0,1] and requires linear base')
    if tail_elision and not (bounded_activity and scheduled_mix):
        raise ValueError('Tail elision requires bounded activity and scheduled mix')
    if render_stride not in (1,2) or (render_stride!=1 and not (bounded_activity and scheduled_mix)):
        raise ValueError('Render stride must be 1 or 2; stride 2 requires bounded activity and scheduled mix')
    sample_rate=FS/render_stride
    step_rate=control_rate//render_stride
    block_samples=32//render_stride
    silence_threshold=round(64.e-6*Q) if rounded_dc else 84
    table_shift=24-tanh_bits
    code = ['; GENERATED by tools/generate_bd.py. Edit the generator, then regenerate.',
            '; Signal path derived from Simple606; see LICENSE-Simple606.',
            '; No timing qualification: draft only.']
    tables = {}
    resident = {}
    if resident_state: code.append('; Hot state stays in spare R/N registers within RENDER; persistent layout is unchanged.')
    if lcg_noise: code.append('; Approximation: replace xorshift32 with the full-period 24-bit LCG used by the metal candidate.')
    if control_rate!=1: code.append(f'; Approximation: interpolate envelope/pitch endpoints every {control_rate} samples; remainder slots hold steps.')
    if simple_impulse: code.append('; Approximation: use a one-pole impulse high-pass in place of the original biquad.')
    if omit_impulse: code.append('; Approximation: omit the differentiated-body impulse layer; body and click controls remain.')
    if sequential_tanh: code.append('; Exact: adjacent tanh reads use a single pointer; fraction arithmetic hides its setup latency.')
    if quadratic_saturation: code.append('; Approximation: clipped quadratic soft saturation replaces both tanh stages.')
    if recursive_body: code.append('; Approximation: magic-circle body oscillator, mean pitch per block; lastbody/z1/z2 hold x/y/coefficient.')
    if lean_mix: code.append('; Approximation: raw LCG click and body share the body low-pass; noise DC/click filters are bypassed.')
    if bounded_activity: code.append('; Exact: specialize positive-envelope blocks and zero-envelope tails; preserve RNG, oscillator and lifetime state.')
    if scheduled_mix: code.append('; Exact: schedule mixer/DC dependencies and cache invariant coefficients in spare registers.')
    if rounded_dc: code.append('; Approximation: rounded DC feedback; 64e-6 lifetime threshold exceeds its quiet rounding floor.')
    if linear_base: code.append(f'; Approximation: first saturation becomes linear gain {linear_base_gain}; plugin HEAT saturation remains.')
    if tail_elision: code.append('; Exact audio: elide inaudible tail oscillator updates and advance the LCG in one jump; dead x/y oscillator state differs.')
    if render_stride!=1: code.append('; Approximation: 22050 Hz engine with causal linear interpolation; output controls and lifetime use 44100 Hz frames.')
    def emit(*lines): code.extend(lines)
    def load(name, reg='a'): emit(f'    move {resident.get(name,S[name])},{reg}')
    def save(name, reg='a1'): emit(f'    move {reg},{resident.get(name,S[name])}')
    def output():
        if render_stride==1:
            emit('    move a,y:(r7)+')
        else:
            # Limit to the actual 24-bit output before interpolation. History
            # persists across TRIG; INIT clears it for dirty-state reassignment.
            emit('    move a,x0'); load('upsample'); save('upsample','x0')
            emit('    add x0,a','    asr #1,a,a','    move a,y:(r7)+','    move x0,y:(r7)+')
    def imm(value, reg='x0'): emit(f'    move #>${word(value):06x},{reg}')
    def mul(value):
        shift = 0
        while abs(value) >= 1:
            value /= 2; shift += 1
        emit('    move a1,x0')
        if scheduled_mix and quadratic_saturation and value==.92+.18*.10: emit('    move r0,y0')
        else: imm(value,'y0')
        emit('    mpy x0,y0,a')
        if shift: emit(f'    asl #{shift},a,a')
    def param(index):
        emit(f'    move y:(r6+${index+1:x}),a', '    asr #7,a,a',
             '    and #>$7f,a', '    move a1,n0')
    def lookup(label, state):
        emit(f'    move #>{label},r0', '    nop', '    move p:(r0+n0),x0')
        save(state,'x0')
    def decay(env, coefficient):
        if control_rate!=1:
            load(env); load(env+'err','x0'); emit('    add x0,a'); save(env)
            return
        load(env,'x0'); load(coefficient,'y0'); emit('    mpy x0,y0,a')
        # Retain sub-word decay updates instead of shortening quiet tails.
        emit('    clr b'); load(env+'err','b0'); emit('    add b,a'); save(env+'err','a0')
        # Match the source's 1e-6 cutoff, with body stored at half amplitude.
        threshold = 4 if env=='amp' else 8
        # CLR changes CCR: prepare zero before CMP so TLT sees the threshold result.
        emit(f'    move #>{threshold},x0', '    clr b', '    cmp x0,a', '    tlt b,a')
        save(env)
    def lowpass(state, hz):
        load(state,'x0'); emit('    sub x0,a', '    move a1,y0')
        if not (scheduled_mix and quadratic_saturation and state=='bodylp'):
            imm(1-math.exp(-2*math.pi*hz/sample_rate),'x1')
        emit('    mpy x1,y0,a', '    add x0,a'); save(state)
    def tanh(heat=False):
        # Q21 input, linear interpolation over 2**tanh_bits intervals on [-4,4].
        if quadratic_saturation:
            # F(x)=x*(1-|x|/4), clamped to x in [-2,2]. In Q21 this is
            # a-a*abs(a). Without impulse, the body/click input is bounded
            # below 1.49, so only the heat stage needs explicit clamps.
            if heat:
                emit('    move #>$400000,x0','    cmp x0,a','    tgt x0,a',
                     '    move #>$c00000,x0','    cmp x0,a','    tlt x0,a')
            emit('    abs a a1,x0','    move a1,y0','    mpy x0,y0,a','    neg a','    add x0,a')
            return
        if sequential_tanh:
            # M0 is linear at the MDS entry point. R0 is scratch, so advance it
            # through adjacent table entries instead of loading two bases.
            emit('    move a1,b',f'    asr #{table_shift},a,a',
                 f'    add #>tanh_table+{1<<(tanh_bits-1)},a','    move a1,r0',
                 f'    and #>${(1<<table_shift)-1:x},b',f'    asl #{23-table_shift},b,b','    move b1,y1',
                 '    move p:(r0)+,x0','    move p:(r0),a',
                 '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a')
            return
        emit('    move a1,b',f'    and #>${(1<<table_shift)-1:x},b',f'    asl #{23-table_shift},b,b','    move b1,y1',
             f'    asr #{table_shift},a,a', f'    add #>${1<<(tanh_bits-1):06x},a', '    move a1,n0',
             '    move #>tanh_table,r0','    nop','    move p:(r0+n0),x0',
             '    move #>tanh_table+1,r0','    nop','    move p:(r0+n0),a',
             '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a')
    emit('init:', '    clr a')
    for name in state_layout(control_rate,render_stride): save(name)
    effective_seed=(seed or 0x606606) if seed is not None else 0x606606
    emit(f'    move #>${effective_seed&0xffffff:06x},x0'); save('rnglo','x0')
    if seed is not None:
        emit(f'    move #>${effective_seed>>24:06x},x0'); save('rnghi','x0')
    emit('    rts', 'trigger:')
    param(0)
    for name in ('amp','freq','pitch','clickcoef','impcoef','clickgain','impgain'):
        if omit_impulse and name.startswith('imp'): continue
        lookup('t_'+name,name)
    # Envelopes use max(old,new), as in DecayEnvelope::trigger().
    load('clickenv','y0'); lookup('t_clickenv','temp'); load('temp')
    emit('    cmp y0,a', '    tlt y0,a'); save('clickenv')
    if not omit_impulse:
        load('impenv','y0'); lookup('t_impenv','temp'); load('temp')
        emit('    cmp y0,a', '    tlt y0,a'); save('impenv')
    param(2)
    lookup('t_tune','temp')
    load('freq','x0'); load('temp','y0'); emit('    mpy x0,y0,a','    asl #2,a,a'); save('freq')
    emit(f'    move #>{round(51.24*(1<<30)/FS)},x0','    mpy x0,y0,a','    asl #2,a,a'); save('target')
    param(1)
    emit('    move y:(r6+$5),a','    tst a','    jeq normal_decay')
    lookup('t_decay_xl','ampcoef'); emit('    jmp decay_ready','normal_decay:')
    lookup('t_decay','ampcoef'); emit('decay_ready:')
    emit(f'    move #>${round((1-.165)*(1<<24)):06x},x0'); save('phase','x0')
    emit('    clr a'); save('lastbody'); save('silent'); save('phasefrac'); save('freqerr'); save('amperr')
    if recursive_body:
        imm(math.cos(-.33*math.pi)/2); save('lastbody','x0')
        imm(math.sin(-.33*math.pi)/2); save('z1','x0')
        save('z2')
    emit('    move #>1,x0'); save('active','x0'); emit('    rts','render:')
    load('active'); emit('    tst a','    jeq silent_block')
    param(3); lookup('t_heatgain','heatgain'); lookup('t_heatnorm','heatnorm')
    if resident_state:
        cached=dict(freq='r1',phase='r2',amp='r3',clickenv='r4',impenv='r5',
                    lastbody='n1',bodylp='n2',clicklp='n3',implp='n4',z1='n5',z2='n6',dcin='n7')
        if omit_impulse:
            for name in ('impenv','lastbody','implp','z1','z2'): cached.pop(name)
            cached.update(amperr='r5',noisein='n1',clickenverr='n4',freqerr='n5',dcout='n6')
        if recursive_body:
            for name in ('freq','phase','freqerr'): cached.pop(name)
            cached.update(lastbody='r1',z1='r2',z2='n5')
        if lean_mix:
            for name in ('noisein','clicklp'): cached.pop(name)
            cached.update(rnglo='n1',clickgain='n3')
        for name,reg in cached.items(): load(name,reg)
        resident.update(cached)
    if control_rate!=1:
        if control_rate!=32: emit(f'    do #{32//control_rate},block_end')
        emit('control_interval:')
        for env,coefficient in (('amp','ampcoef'),('clickenv','clickcoef'),('impenv','impcoef')):
            if omit_impulse and env=='impenv': continue
            # Truncate the endpoint: rounding can pin quiet envelopes above cutoff.
            load(env,'x0'); load(coefficient,'y0'); emit('    mpy x0,y0,a','    clr b',
                f'    move #>{4 if env=="amp" else 8},y1','    cmp y1,a','    tlt b,a'); save(env+'next')
            emit('    move a1,a','    sub x0,a',f'    add #>{step_rate-1},a',f'    asr #{int(math.log2(step_rate))},a,a'); save(env+'err')
        load('target'); load('freq','x0'); emit('    sub x0,a','    move a1,y0'); load('pitch','x1')
        emit('    mpy x1,y0,a','    add x0,a'); save('freqnext')
        emit('    move a1,a','    sub x0,a',f'    add #>{step_rate-1},a',f'    asr #{int(math.log2(step_rate))},a,a'); save('freqerr')
        if recursive_body:
            # Frequency retains the full-rate Q30 scale so maximum tune fits
            # signed 24 bits. Stride 2 doubles the sine-table phase, not storage.
            phase_shift=16-int(math.log2(render_stride))
            load('freq','x0'); load('freqnext'); emit('    add x0,a')
            load('freqerr','x0'); emit('    add x0,a','    asr #1,a,a','    move a1,b',
                f'    asr #{phase_shift},a,a','    move a1,r0',f'    and #>${(1<<phase_shift)-1:x},b',f'    asl #{23-phase_shift},b,b','    move b1,y1',
                '    move x:(r0+>mds_sine),x0','    move x:(r0+>mds_sine+1),a',
                '    sub x0,a','    move a1,x1','    mpy x1,y1,a','    add x0,a','    asl #1,a,a','    rnd a')
            load('z2','x0'); save('z2'); emit('    move a1,a','    sub x0,a','    asr #1,a,a','    move a1,x0')
            load('z1','y0'); load('lastbody'); emit('    mac x0,y0,a'); save('lastbody')
        if scheduled_mix:
            imm(.995**render_stride,'n0')
            if quadratic_saturation:
                imm(.92+.18*.10,'r0')
                imm(1-math.exp(-2*math.pi*(620+(1200-620)*.34)/sample_rate),'x1')
        loop_start=len(code)
        emit(f'    do #{step_rate},control_samples_end','sample:')
    else: emit('    do #32,block_end','sample:')
    active_check_start=len(code)
    load('active'); emit('    tst a','    jeq sample_silent')
    sample_body_start=len(code)
    noise_start=len(code)
    # Exact xorshift32 expressed as a low-24/high-8 pair.
    load('rnglo','x0'); load('rnglo'); emit('    asl #13,a,a', '    eor x0,a'); save('rngtemp')
    load('rnglo'); emit('    asr #11,a,a','    and #>$ff,a'); load('rnghi','x0')
    emit('    eor x0,a'); save('rnghi')
    # ASR leaves discarded bits in A0; clear them before the next left shift.
    load('rnghi')
    emit('    asl #7,a,a','    move a1,x0'); load('rngtemp')
    emit('    asr #17,a,a','    and #>$7f,a','    or x0,a'); load('rngtemp','x0')
    emit('    eor x0,a'); save('rngtemp')
    emit('    asr #19,a,a','    and #>$1f,a','    move a1,x0'); load('rnghi')
    emit('    asl #5,a,a','    or x0,a'); load('rnghi','x0')
    emit('    eor x0,a','    and #>$ff,a'); save('rnghi')
    load('rngtemp'); emit('    asl #5,a,a'); load('rngtemp','x0'); emit('    eor x0,a'); save('rnglo')
    emit('    asr #9,a,a','    and #>$7fff,a','    move a1,x0'); load('rnghi')
    emit('    asl #15,a,a','    or x0,a','    sub #>$400000,a','    asr #1,a,a')
    if lcg_noise:
        code[noise_start:]=[]
        load('rnglo','x0'); emit('    move #>$19660d,y0','    mpy x0,y0,a','    asr #1,a,a',
                               '    move a0,a','    add #>$6ef35f,a'); save('rnglo')
        noise_state_end=len(code)
        emit('    move #>$800000,x0','    eor x0,a','    move a1,a','    asr #2,a,a')
    if lean_mix:
        emit('    move a1,b')
        if scheduled_mix:
            load('clickenv'); load('clickenverr','x0')
            emit('    add x0,a','    move b1,x0','    move a1,y0',
                 f'    mpy x0,y0,a a1,{resident["clickenv"]}')
        else:
            decay('clickenv','clickcoef'); emit('    move a1,y0','    move b1,x0','    mpy x0,y0,a')
    else:
        # DC-filtered noise, scaled /4.
        load('noisein','x0'); save('noisein'); emit('    sub x0,a','    move a1,b')
        load('noiseout'); mul(.995); emit('    add b,a'); save('noiseout')
        lowpass('clicklp',1400)
        decay('clickenv','clickcoef'); emit('    move a1,y0'); load('clicklp','x0'); emit('    mpy x0,y0,a')
    load('clickgain','y0'); emit('    move a1,x0','    mpy x0,y0,a'); save('click')
    body_osc_start=len(code)
    if recursive_body:
        # Oscillator states are Q22, leaving headroom around the unit circle.
        load('z1','x0'); load('z2','y0'); load('lastbody')
        emit('    mac -x0,y0,a x0,y1','    move a1,x0',
             f'    tfr y1,a a1,{resident["lastbody"]}', '    mac x0,y0,a')
        if scheduled_mix: load('amp','y0'); emit('    move a1,x0')
        else: emit('    move a1,x0'); load('amp','y0')
        emit(f'    mpy x0,y0,a a1,{resident["z1"]}')
        body_osc_end=len(code)
    else:
        # Swept sine body. Frequency changes before the phase increment, as upstream.
        if control_rate!=1:
            load('freq'); load('freqerr','x0'); emit('    add x0,a'); save('freq')
        else:
            load('target'); load('freq','x0'); emit('    sub x0,a','    move a1,y0'); load('pitch','x1')
            emit('    mpy x1,y0,a','    clr b'); load('freqerr','b0')
            emit('    add b,a'); save('freqerr','a0'); emit('    add x0,a'); save('freq')
        # Six fractional frequency bits prevent cumulative pitch-sweep truncation.
        load('phasefrac','x0'); emit('    add x0,a','    move a1,b','    and #>$3f,b'); save('phasefrac','b1')
        emit('    asr #6,a,a'); load('phase','x0'); emit('    add x0,a'); save('phase')
        # Nearest sine index avoids a one-sided phase error amplified by HEAT.
        # Keep the full-rate reference's lookup unchanged.
        if control_rate!=1: emit('    add #>$100,a')
        emit('    asr #9,a,a','    and #>$7fff,a','    move a1,r0',
             '    move x:(r0+>mds_sine),x0')
        load('amp','y0'); emit('    mpy x0,y0,a','    asr #1,a,a')
    if omit_impulse:
        if not scheduled_mix: emit('    move a1,a')
    else:
        load('lastbody','x0'); save('lastbody'); emit('    move a1,b','    sub x0,a'); save('delta')
        emit('    move b1,a')
    if not lean_mix: lowpass('bodylp',620+(1200-620)*.34)
    mul(.92+.18*.10)
    if scheduled_mix:
        load('amp','b'); load('amperr','x0')
        save('body'); emit('    add x0,b','    move a1,a')
        save('amp','b1')
    else: save('body'); decay('amp','ampcoef')
    # Impulse: differentiated body -> source high-pass biquad -> low-pass.
    w=2*math.pi*1350/sample_rate; c=math.cos(w); alpha=math.sin(w)/(2*.707); norm=1/(1+alpha)
    b0=(1+c)*.5*norm; b1=-(1+c)*norm; b2=b0; a1=-2*c*norm; a2=(1-alpha)*norm
    impulse_start=len(code)
    if simple_impulse:
        load('delta'); lowpass('z1',1350)
        load('delta','x0'); emit('    neg a','    add x0,a'); lowpass('implp',2600)
    else:
        load('delta'); mul(b0); load('z1','x0'); emit('    add x0,a'); save('temp')
        load('delta'); mul(b1); emit('    move a1,b'); load('temp'); mul(-a1)
        emit('    add b,a'); load('z2','x0'); emit('    add x0,a'); save('z1')
        load('delta'); mul(b2); emit('    move a1,b'); load('temp'); mul(-a2)
        emit('    add b,a'); save('z2'); load('temp'); lowpass('implp',2600)
    decay('impenv','impcoef'); emit('    move a1,y0'); load('implp','x0')
    emit('    mpy x0,y0,a','    move a1,x0'); load('impgain','y0')
    emit('    mpy x0,y0,a','    asl #1,a,a'); load('body','x0'); emit('    add x0,a')
    if omit_impulse:
        code[impulse_start:]=[]
        if not scheduled_mix: load('body')
    load('click','x0'); emit('    add x0,a')
    mix_filter_start=len(code)
    if lean_mix: lowpass('bodylp',620+(1200-620)*.34)
    mul((1.12+.18*.12)*(linear_base_gain if linear_base else 1))
    if not linear_base: tanh()
    # Output DC blocker and source voice trim.
    load('dcin','x0')
    if scheduled_mix:
        emit(f'    sub x0,a a1,{resident["dcin"]}',
             '    move n0,y0','    move a1,y1')
        load('dcout','x0')
        if rounded_dc: emit('    mpyr x0,y0,a')
        else:
            emit('    mpy x0,y0,a','    clr b')
            load('dcerr','b0'); emit('    add b,a'); save('dcerr','a0')
        emit('    add y1,a')
    else:
        save('dcin'); emit('    sub x0,a','    move a1,b')
        load('dcout'); mul(.995)
        emit('    move b1,y0','    clr b'); load('dcerr','b0')
        emit('    add b,a'); save('dcerr','a0'); emit('    add y0,a')
    save('dcout'); mul(.70)
    emit('    move a1,b', '    asl #2,b,b'); save('temp','b1')
    # Plugin heat is evaluated per render, rather than captured at trigger.
    if resident_state:
        # B is free here. Preserve the old A1-to-A truncation before testing heat.
        emit('    move a1,a','    move y:(r6+$4),b','    tst b','    jeq heat_done')
    else:
        emit('    move y:(r6+$4),x0','    move a1,b','    move x0,a','    tst a',
             '    move b1,a','    jeq heat_done')
    load('heatgain','y0'); emit('    move a1,x0','    mpy x0,y0,a','    asl #3,a,a'); tanh(heat=True)
    load('heatnorm','y0'); emit('    move a1,x0','    mpy x0,y0,a','heat_done:')
    emit('    asl #2,a,a'); output()
    sample_output_end=len(code)
    load('amp'); load('clickenv','x0'); emit('    or x0,a')
    if not omit_impulse: load('impenv','x0'); emit('    or x0,a')
    emit('    jne reset_silence')
    load('temp'); emit('    abs a',f'    move #>{silence_threshold},x0','    cmp x0,a','    jge reset_silence')
    load('silent'); emit(f'    add #>{render_stride},a'); save('silent')
    emit('    move #>32,x0','    cmp x0,a','    jlt sample_done','    clr a'); save('active')
    emit('    jmp sample_done','reset_silence:','    clr a'); save('silent')
    emit('    jmp sample_done','sample_silent:','    clr a'); output()
    emit('sample_done:','    nop')
    sample_end=len(code)
    if control_rate!=1:
        emit('control_samples_end:')
        for name in ('amp','clickenv','impenv','freq'):
            if omit_impulse and name=='impenv': continue
            load(name+'next'); save(name)
        emit('    nop')
    emit('block_end:')
    if resident_state:
        resident.clear()
        for name,reg in cached.items(): save(name,reg)
    emit('    rts','silent_block:','    clr a')
    if render_stride!=1: output(); emit('    clr a')
    emit(f'    do #{32 if render_stride==1 else 30},zero_end',
         '    move a,y:(r7)+','zero_end:','    rts')
    if bounded_activity:
        # Steps round toward zero, so the nonincreasing envelope's final
        # sample is its minimum. A positive minimum proves every lifetime
        # check resets SILENT and ACTIVE cannot clear within this block.
        # Keep the complete slow loop for zero-envelope/output-filter tails.
        def rename(lines,suffix):
            labels=[line[:-1] for line in lines if line.endswith(':')]
            for label in labels:
                lines=[re.sub(r'\b'+re.escape(label)+r'\b',label+suffix,line) for line in lines]
            return lines
        fast=rename(code[sample_body_start:sample_output_end],'_bounded')
        # When both envelopes already equal zero, their steps also equal zero.
        # RNG and oscillator state still advance exactly. Their products and
        # gain/envelope work can be omitted; preserve the filter/output tail
        # and its per-sample activity decisions, including mid-block silence.
        tail=rename(code[active_check_start:noise_state_end]+
                    code[body_osc_start:body_osc_end]+['    move a1,a']+
                    code[mix_filter_start:sample_end],'_tail')
        if tail_elision:
            tail=code[active_check_start:sample_body_start]+['    clr a']+code[mix_filter_start:sample_end]
            stop=tail.index(f'    move a1,{S["active"]}')+1
            # LC counts the current iteration: block_samples+1-LC counts
            # actual draws including the stopping sample (16 or 32 at most).
            tail[stop:stop]=['    move lc,a','    neg a',f'    add #>{block_samples+1},a',f'    move a1,{cached["lastbody"]}']
            tail=rename(tail,'_tail')
        if scheduled_mix:
            # A positive initial envelope cannot reach zero before sample N:
            # d=ceil((next-current)/N), with 0<=next<=current. If d<0 and
            # current+N*d==0, samples 1..N-1 are still strictly positive.
            # Thus SILENT resets in those samples and can only advance at
            # the last sample. This removes the fallback loop completely.
            prelude=[f'    move {cached["amp"]},a',f'    move {cached["clickenv"]},x0',
                '    or x0,a','    jeq activity_tail','    clr a',
                f'    move a1,{S["silent"]}',f'    do #{block_samples},activity_fast_end']
            final_lifetime=[f'    move {cached["amp"]},a',f'    move {cached["clickenv"]},x0',
                '    or x0,a','    jne control_samples_end',f'    move {S["temp"]},a',
                '    abs a',f'    move #>{silence_threshold},x0','    cmp x0,a','    jge control_samples_end',
                f'    move #>{render_stride},x0',f'    move x0,{S["silent"]}','    jmp control_samples_end']
            tail_setup=['activity_tail:','    clr a',f'    move a1,{S["body"]}',f'    move a1,{S["click"]}']
            tail_finish=[]
            if tail_elision:
                tail_setup += [f'    move {cached["lastbody"]},{S["lastbody"]}',f'    move #>{block_samples},{cached["lastbody"]}']
                tail_finish=[f'    move {cached["lastbody"]},a','    asl #1,a,a',
                    '    add #>t_rng_jump,a','    move a1,r0',f'    move {cached["rnglo"]},x0',
                    '    move p:(r0)+,y0','    mpy x0,y0,a','    asr #1,a,a','    move a0,a',
                    '    move p:(r0),x0','    add x0,a',f'    move a1,{cached["rnglo"]}',
                    f'    move {S["lastbody"]},{cached["lastbody"]}']
            code[loop_start:sample_end]=prelude+fast+['    nop','activity_fast_end:']+final_lifetime+tail_setup+[
                f'    do #{block_samples},activity_tail_end']+tail+['activity_tail_end:']+tail_finish
        else:
            prelude=[f'    move {cached["amp"]},a',f'    move {cached["clickenv"]},x0',
                 '    or x0,a','    jeq activity_tail',
                 f'    move {cached["amperr"]},a','    asl #5,a,a',
                 f'    move {cached["amp"]},x0','    add x0,a',
                 '    tst a','    jle activity_slow','    clr a',
                 f'    move a1,{S["silent"]}',f'    do #{block_samples},activity_fast_end']
            code[loop_start:loop_start]=prelude+fast+['    nop','activity_fast_end:',
                '    jmp control_samples_end','activity_tail:','    clr a',
                f'    move a1,{S["body"]}',f'    move a1,{S["click"]}',
                '    do #32,activity_tail_end']+tail+['activity_tail_end:',
                '    jmp control_samples_end','activity_slow:']
    for name in ('amp','freq','pitch','clickenv','clickcoef','impenv','impcoef','clickgain','impgain'):
        if omit_impulse and name.startswith('imp'): continue
        tables['t_'+name]=[]
    for i in range(128):
        transient=(i/127)**.75; shape=.1+transient*.5; thud=shape*shape
        values=dict(amp=(1+thud*.22)/2, freq=116.48*(1+thud*.28)*128/FS,
                    pitch=1-math.exp(-1/(sample_rate*(.022-.014*thud))),
                    clickenv=.04+shape*.34, clickcoef=math.exp(-1/(sample_rate*(.002+shape*.0085))),
                    impenv=.06+shape*.55+thud*.08, impcoef=math.exp(-1/(sample_rate*(.0008+shape*.008))),
                    clickgain=(.06+shape*.9)/math.sqrt(render_stride), impgain=(.08+shape*2.2)/2)
        if control_rate!=1:
            values['pitch']=1-(1-values['pitch'])**step_rate
            for coefficient in ('clickcoef','impcoef'): values[coefficient]**=step_rate
        for name,value in values.items():
            if omit_impulse and name.startswith('imp'): continue
            tables['t_'+name].append(word(value))
    tables['t_tune']=[word(2**((-12+24*i/127)/12)/4) for i in range(128)]
    for name,scale in (('t_decay',.45),('t_decay_xl',1)):
        tables[name]=[word(math.exp(-step_rate/(sample_rate*(.22+(-1.75+4.75*(i/127*scale)**2)*.12)))) for i in range(128)]
    tables['t_heatgain']=[word((1+3.5*i/127)/8) for i in range(128)]
    tables['t_heatnorm']=[word(1/math.sqrt(1+3.5*i/127)) for i in range(128)]
    if tail_elision:
        # Integer affine composition modulo 2**24; not fractional coefficients.
        jump_a,jump_b=1,0; tables['t_rng_jump']=[]
        for _ in range(block_samples+1):
            tables['t_rng_jump'] += [jump_a,jump_b]
            jump_a=(1664525*jump_a)&0xffffff
            jump_b=(1664525*jump_b+1013904223)&0xffffff
    if not quadratic_saturation:
        tables['tanh_table']=[word(math.tanh((i-(1<<(tanh_bits-1)))/(1<<(tanh_bits-3)))/4) for i in range((1<<tanh_bits)+1)]
    for name,values in tables.items():
        emit(name+':')
        for i in range(0,len(values),8): emit('    .dc '+','.join(f'${w:06x}' for w in values[i:i+8]))
    return '\n'.join(code)+'\n'


def main():
    destination=ROOT/'machines/bd'
    destination.mkdir(parents=True,exist_ok=True)
    (destination/'bd.asm').write_text(generate())
    manifest=dict(id='org.kitbasher.tr6.bd',display_name='TR6 BASS DRUM',category='TR6',short_label='BD',
                  machine_version='0.1', params=[
        dict(name='TRAN',default=51,transform='raw14'),
        dict(name='DEC',default=102,transform='raw14'),
        dict(name='TUNE',default=75,transform='raw14'),
        dict(name='HEAT',default=0,transform='raw14'),
        dict(name='XL',default=0,transform='boolean')])
    (destination/'bd.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(destination)


if __name__=='__main__': main()
